{
 "title": "Loki flog example",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flogs\"}"
    }
   ]
  },
  {
   "title": "Simplified logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flogs\"} | json | line_format \"{{ .method }} {{ .request }} 👉 {{ .status }} by {{ .user_identifier }} ({{div .bytes 1000}} kb)\" "
    }
   ]
  },
  {
   "title": "Max size per HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time({job=\"flogs\"} | json | unwrap bytes[5m]) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max size per HTTP method",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time({job=\"flogs\"} | json | unwrap bytes[5m]) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Distribution by method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({job=\"flogs\"} | json [5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Distribution by status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"flogs\"} | json [5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Distribution by protocol",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (protocol) (count_over_time({job=\"flogs\"} | json [5m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Identified requests (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flogs\"} | json | user_identifier != \"-\" [5m])) / sum(count_over_time({job=\"flogs\"} [5m]))"
    }
   ]
  },
  {
   "title": "> 10kb (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flogs\"} | json | bytes > 10000[5m])) / sum(count_over_time({job=\"flogs\"} | json [5m])) * 100"
    }
   ]
  },
  {
   "title": "Total lines (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"flogs\"}[5m])"
    }
   ]
  },
  {
   "title": "Lines/sec (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate({job=\"flogs\"}[5m])"
    }
   ]
  },
  {
   "title": "Largest request body (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time({job=\"flogs\"} | json | unwrap bytes[5m]))"
    }
   ]
  },
  {
   "title": "Bytes/sec (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bytes_rate({job=\"flogs\"}[5m])"
    }
   ]
  }
 ]
}