---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: navidrome
    template:
      engineVersion: v2
      data:
        ND_LASTFM_APIKEY: "{{ .LASTFM_APIKEY }}"
        ND_LASTFM_SECRET: "{{ .LASTFM_SECRET }}"
        ND_INITIALADMINPASSWORD: "{{ .NAVIDROME_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: navidrome
