---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  chartRef:
    kind: OCIRepository
    name: navidrome
  values:
    controllers:
      navidrome:
        containers:
          app:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.58.5
            envFrom:
              - secretRef:
                  name: navidrome
            env:
              TZ: "${TIMEZONE}"
              ND_DATAFOLDER: /config
              ND_MUSICFOLDER: /music
              ND_ENABLEGRAVATAR: "true"
              ND_LOGLEVEL: info
              ND_DEFAULTTHEME: Spotify-ish
              ND_PORT: &port 8080
              ND_PROMETHEUS_ENABLED: "true"
              ND_REVERSEPROXYUSERHEADER: "Remote-User"
              ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
              ND_SCANSCHEDULE: "@every 5m"
              ND_SESSIONTIMEOUT: 24h
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 750Mi
    service:
      app:
        controller: navidrome
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "navidrome.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: navidrome-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      music:
        type: nfs
        server: ${NAS_SERVER_IP}
        path: ${NAS_SERVER_MEDIA_PATH}/Library/Media/Music
        globalMounts:
          - path: /music
            readOnly: true
