---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: vaultwarden
