---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: vaultwarden
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  displayname: Vaultwarden
  origin: https://vault.${SECRET_DOMAIN}/
  redirectUrl:
    - https://vault.${SECRET_DOMAIN}/identity/connect/oidc-signin
  scopeMap:
    - group: vaultwarden_users@idm.${SECRET_DOMAIN}
      scopes:
        - openid
        - profile
        - email
  strictRedirectUrl: true
  disableConsentPrompt: true
