---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gonic
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      gonic:
        containers:
          app:
            image:
              repository: ghcr.io/sentriz/gonic
              tag: v0.22.0@sha256:516fd9645614ba3a596d86174216c3e944808b9ec970c581678713be4c8b1d49
            env:
              TZ: "${TZ}"
              GONIC_LISTEN_ADDR: ":4747"
              GONIC_DB_PATH: /data/gonic.db
              GONIC_CACHE_PATH: /cache
              GONIC_PLAYLISTS_PATH: /playlists
              GONIC_PODCAST_PATH: /podcasts
              GONIC_MUSIC_PATH: collection->/music/collection,mixtapes->/music/mixtapes,podcasts->/music/podcasts
              GONIC_SCAN_INTERVAL: 60
              GONIC_SCAN_AT_START_ENABLED: "true"
              GONIC_SCAN_WATCHER_ENABLED: "false"
              GONIC_EXCLUDE_PATTERN: "@eaDir|[aA]rtwork|[cC]overs|[sS]cans"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 65537
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: gonic
        ports:
          http:
            port: &port 4747
    route:
      app:
        hostnames:
          - "gonic.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: gonic-config
        globalMounts:
          - path: /data
            subPath: data
          - path: /playlists
            subPath: playlists
          - path: /podcasts
            subPath: podcasts
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      tmp:
        type: emptyDir
      collection:
        type: nfs
        server: ${REBOST_IP}
        path: ${REBOST_MEDIA_PATH}/Library/Media/Music/Collection
        globalMounts:
          - path: /music/collection
            readOnly: true
      mixtapes:
        type: nfs
        server: ${REBOST_IP}
        path: ${REBOST_MEDIA_PATH}/Library/Media/Music/Mixtapes
        globalMounts:
          - path: /music/mixtapes
            readOnly: true
      podcasts:
        type: nfs
        server: ${REBOST_IP}
        path: ${REBOST_MEDIA_PATH}/Library/Media/Podcasts
        globalMounts:
          - path: /music/podcasts
            readOnly: true
