---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prom-push-test.yaml
  - ./snapshot.yaml

configMapGenerator:
  - name: prom-push-test
    files:
      - prom-push-test.js=./prom-push-test.js
  - name: prom-push-test-config
    files:
      - prom-push-test.yaml=./prom-push-test.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
