---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: prom-push-test
  labels:
    app: prom-push-test
    k6-scenario: prom-push-test
spec:
  parallelism: 1
  runner:
    image: grafana/k6:2.0.0-with-browser@sha256:880501ca99b97a0e519c7ed6a038d7ce031b4181cf4843066aa97d33936294ad
    resources:
      requests:
        cpu: "100m"
      limits:
        memory: "256Mi"
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/write
  arguments: -o experimental-prometheus-rw --quiet
  script:
    configMap:
      name: prom-push-test
      file: prom-push-test.js
