apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:sjCfvEzbhFwxcYVizg9bcDMAvz2S85ijIwWgfZOQSJfgH7gQFZQYzEkqEI8=,iv:sPVlSa6xOdfWdbjMR+2qxNByp5bVk+mzsov/O9eHAnU=,tag:gAQlg+9LHQmoCVQQg6Obpw==,type:str]
sops:
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbGhwRU1jbkJEdlY2R1N3
            clE4ZzJMY2dJR0lzZzBiT2F6Y0VvenQ0N2hvCk1FMGM4MktMb05DS3ZhM0tLZ1pw
            Vlltazc4NlVLVnZleUQvWEI2TjM3QmsKLS0tIEJaeU9qMm5JUjVLZFlrQ1ZESDEv
            akJvNktVVE03S3QyMVpUMi9TUDBEd1UK/gUNkCYZ+JclF0BwAhJjKQeEh3DYiDYF
            yACPMKWE6wMYeLuQiABiGaNq51QwOGL9Slp4sDqVh0LPwp8LiI04+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T15:49:50Z"
    mac: ENC[AES256_GCM,data:a+EONwyKr6aS3DEobMdttgT5s9dNzvz7nZu4t2cI52ezIaXrvQrQtBixRuKbuTSb8W8FZ7bgTt1BeuC8XIPKXJi8RCjaY71Q0EuQgh9w4/3p7P9pP6k4cMUaQR8Ru1Rn7vykxP8NWOxNnV8Shs/7sSAo29Tk37k3pfyFwv9j9i0=,iv:IX7UrBesgZ16DITTIdWnv99Slhy449SPpRixclcAsNs=,tag:H1wTgPPZdtzOaRjr0s5Nxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
