{
 "title": "Cardinality Explorer",
 "description": "Find cardinality sources",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "query_result( count by (job)(up{}) )"
   },
   {
    "name": "metric",
    "query": "query_result( count by (__name__) ({job=\"$job\" }) )"
   },
   {
    "name": "labels",
    "query": "query_result(topk(32,$metric{job=\"$job\"} ) )"
   },
   {
    "name": "label_names",
    "query": "query_result(topk(32,$metric{job=\"$job\"} ) )"
   }
  ]
 },
 "panels": [
  {
   "title": "how to",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "How To",
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Cardinality Explorer\n[Cardinality](https://www.robustperception.io/cardinality-is-key) is the count at a certain time of the total unique combinations of keys and labels.  Too much (red) is bad, and will make your queries slow and your prometheus run out of memory.  This dashboard will help you analyze individual metrics to determine the cause(s) of cardinality.\n## WARNING\n * This dashboard can be *very* slow and heavy\n * Use with caution\n\n## Instructions\n 1. Choose the datasource which contains your data from the `datasource` dropdown\n 2. Choose a job from the `job` dropdown, which is now populated with the prometheus jobs in your account\n 3. Choose a metric name from the `metric` dropdown, now populated with with the metrics available to the specified job in your account\n 4. Choose the `labels` which you would like to run calculations on\n\n## Understanding the Data\n * The `(metricname) cardinality` row gives you basic information about your metric\n    * The `metric` panel shows the metric name you've chosen\n    * The `cardinality` panel shows the metric's cardinality\n * The `count by label` row shows the number of unique values for every label\n * The `cardinality calculation` row shows information based on the labels you selected in the `labels` dropdown\n    * The `count without()` panel shows what the cardinality of the metric would be if the specified labels were to be removed\n    * The `count by()` panel shows what the cardinality of the specified labels as a group is"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "$metric cardinality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "metric",
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 2 },
   "options": {
    "content": "<center><h1 style=\"color:#2980B9;\">$metric</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "cardinality",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count($metric{job=\"$job\"}) "
    }
   ]
  },
  {
   "title": "count by label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "${label_names}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "repeat": "label_names",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (${label_names})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  {
   "title": "cardinality calculation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "count without (${labels:csv})",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count without (${labels:csv})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  {
   "title": "count by (${labels:csv})",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (${labels:csv})( $metric{job=\"$job\"}) )"
    }
   ]
  },
  {
   "title": "faq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Frequently Asked Questions",
     "type": "text",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "<h1>FAQ</h1>\n<ul>\n <li> Why doesn't <code>count without</code> * <code>count by</code> = <code>cardinality</code>?</li>\n  <ul>\n   <li> Cardinality is only concerned with existing label/value combinations, not potential ones.  Consider a simple case of a metric with two labels and two possible values for each label.  There are four possible combinations of label values, but if one value only shows up once, then the cardinality will be only three.</li>\n   <li> Example:\n    <table>\n     <tr>\n      <th>label1</th><th>label2</th>\n     </tr>\n     <tr>\n      <td>A</td><td>200</td>\n     </tr>\n     <tr>\n      <td>A</td><td>404</td>\n     </tr>\n     <tr>\n      <td>B</td><td>404</td>\n     </tr>\n    </table>\n   </li>\n  </ul>\n\n <li>This dashboard might help investigating cardinality for individual metrics, but how do I find high-cardinality metrics in the first place?</li>\n  <ul>\n   <li><a href=\"https://www.robustperception.io/which-are-my-biggest-metrics\">query</a> for it: <code>topk(10, count by (__name__)({__name__=~\".+\"}))\n</code></li>\n   <li>use <a href=\"https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality\">tsdb</a></li>\n  </ul>\n <li>What should I do with high-cardinality labels?</li>\n  <ul>\n   <li>Consider whether you can <a href=\"https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus\">drop</a> them.</li>\n  </ul>\n</ul>\n  \n  \n"
     },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}