---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-develop
  namespace: flux-system
spec:
  inputs:
  - app: forgejo-workspace-config
    namespace: develop
    path: ./kubernetes/apps/develop/workspace/config
