---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-flux-system
  namespace: flux-system
spec:
  inputs:
  - namespace: flux-system
    apps:
    - app: flux-instance
      dependsOn:
      - name: flux-operator
    - app: flux-operator
      wait: true
