apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: observability
type: Opaque
stringData:
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:Sc2kUKukdQ5/I2Qph9O8rQIfFg7hWeYBncsh9V82,iv:g62TNE1SHgV+/8YMIq5u1QyrVCv/cM3lSNgdM4N1YK8=,tag:dmYguzQErisl82MG/KbSkQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:M98gtsJOwVt1JYsv2MMym+1j+MvTG3bHffGuMwZc,iv:GDahDTLKCEfeGKHuR32DuvOWBATX162RBu7tx2TMo3k=,tag:tXue5HbhTwwlltr7chsf4w==,type:str]
    ALLQUIET_WEBHOOK_URL: ENC[AES256_GCM,data:LrLf4C3Q1TcFoJouYUDZrgiGOo1017Q4YbNhZStTTb6pdLt8xvSLOV/DvRH7DQgWhl2EWe+d8Yn1naakNtlW/BhUKfM=,iv:56ydtjFqzSmc05tUjvpEj7V+1ZVbMS3g642+sLHYmf4=,tag:7twQJsknYOBmBkVK0L2lBw==,type:str]
sops:
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRFd0TklUaVlwNU1iMENI
            UUZCSzhveFhPZXRiYVdsK3RoVERkeHQwZ1hzCkZOdFlWSzFBOGMxd2VadVhWbktV
            cTRSa3M1R3RBTEJWMmpLSXlsREhhZWsKLS0tIDJVT3Jpb3FlTDdJV3FveG5DK1lm
            dnA2TnBoWUFqUUVEdVJYVjU2a3NLb3MKWg17djOKiDUTd3UuP50E/HWyfq1FuOX5
            S3SMEQtLhgU4fpImbSUiSxOkLgd+hk7YhmLA2dnA4T77C9cHu53S5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T09:47:18Z"
    mac: ENC[AES256_GCM,data:3ZnIM+M1O3aYc72Uy+eFbmlLSE+gIrVffbAtOGb1hjHqIiBN3eNvroGuqPrT7jksKWaItRTIw30o05yGyY0sqOJrp3R+BmTLWk8DgktL3WylAAtxIbBA3jUYbe2dq9oqe0nfz152UxCi/ZJVygESeC+UvESwR0dfZH4fQhlylv8=,iv:7nF1kfqyOhB9imONal1cwWf/4h7ygyfYGUAxqCTvHWI=,tag:cQstTEvZDaSKyANbdcd03A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
