prometheus:
  route:
    main:
      enabled: true
      hostnames:
        - prometheus.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
  prometheusSpec:
    replicas: 1
    externalUrl: https://prometheus.${SECRET_DOMAIN}
    replicaExternalLabelName: __replica__
    scrapeInterval: 1m
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    enableAdminAPI: true
    enableFeatures:
      - exemplar-storage
    walCompression: true
    enableRemoteWriteReceiver: true
    retention: 14d
    retentionSize: 15GB
    externalLabels:
      cluster: apps
      env: homelab
    additionalAlertRelabelConfigs:
      - source_labels: [alertname, cluster, env]
        separator: ' · '
        regex: '(.+) · (.+) · (.+)'
        replacement: '$1 — $2/$3'
        target_label: alert_title
      - source_labels: [node]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [instance]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [pod]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [container]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [resourcequota]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [persistentvolumeclaim]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [horizontalpodautoscaler]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [daemonset]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [statefulset]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [deployment]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [job_name]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [cronjob]
        regex: '(.+)'
        target_label: __resource
      - source_labels: [alertname, __resource, cluster, env]
        separator: ' · '
        regex: '(.+) · (.+) · (.+) · (.+)'
        replacement: '$1 — $2 · $3/$4'
        target_label: alert_title
      - source_labels: [alertname, __resource, namespace, cluster, env]
        separator: ' · '
        regex: '(.+) · (.+) · (.+) · (.+) · (.+)'
        replacement: '$1 — $2 · $3 · $4/$5'
        target_label: alert_title
      - source_labels: [alertname, job, namespace, cluster, env]
        separator: ' · '
        regex: 'TargetDown · (.+) · (.+) · (.+) · (.+)'
        replacement: 'TargetDown — $1 · $2 · $3/$4'
        target_label: alert_title
      - regex: __resource
        action: labeldrop
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 1500Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: 20Gi
    additionalRulesForClusterRole:
      - apiGroups: [""]
        resources: ["services/k6-operator-controller-manager-metrics-service"]
        verbs: ["get", "list", "watch"]
