---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgejo-workspace
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: forgejo-workspace-auth
  url: ssh://git@git.oscaromeu.io/oscar/work-ops.git
