---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: clickhouse-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.4
    digest: sha256:4ddc5e7aee10b6a96ea15f6f2e79f1dc0800ad59e514fe982241dc724825a388
  url: oci://ghcr.io/clickhouse/clickhouse-operator-helm
