---
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  TALOS_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER | default "home"}}'
  TERRAFORM_DIR: '{{.ROOT_DIR}}/terraform'
  PRIVATE_DIR: '{{.ROOT_DIR}}/.private'
  TALOSCONFIG: '{{.ROOT_DIR}}/talos/{{.CLUSTER | default "home"}}/clusterconfig/talosconfig'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{env "HOME"}}/.config/sops/age/home-ops.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  ansible: .taskfiles/ansible
  bootstrap: .taskfiles/bootstrap
  rs: .taskfiles/rs
  talos: .taskfiles/talos
  utils: .taskfiles/utils
  terragrunt: .taskfiles/terragrunt

tasks:

  default: task --list

  reconcile:
    desc: Force Flux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which flux
