---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 30m
  values:
    ai:
      enabled: false
    controller:
      excludedNamespaces:
        - kguardian
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
    broker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 512Mi
    database:
      enabled: false
      user: kguardian
      databaseName: kguardian
      existingSecret: kguardian-postgres-credentials
      passwordSecretKey: password
      external:
        host: postgres-${postgres_cluster_version}-primary.databases.svc
        port: 5432
        sslMode: prefer
    telemetry:
      enabled: false
