---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: not-used
spec:
  resourcesTemplate: |
    <<- $ns := dig "namespace" "default" (inputs) >>
    <<- range $app := inputs.apps >>
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << $app.app >>
      namespace: flux-system
    spec:
      interval: 1h
      prune: true
      deletionPolicy: WaitForTermination
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      path: << dig "path" (printf "./kubernetes/apps/%s/%s/app" $ns $app.app) $app >>
      targetNamespace: << dig "targetNamespace" $ns $app >>
      decryption:
        provider: sops
      <<- if hasKey $app "components" >>
      components: << toYaml $app.components | nindent 8 >>
      <<- end >>
      <<- if hasKey $app "dependsOn" >>
      dependsOn: << toYaml $app.dependsOn | nindent 8 >>
      <<- end >>
      <<- if hasKey $app "healthChecks" >>
      healthChecks: << toYaml $app.healthChecks | nindent 8 >>
      <<- end >>
      <<- if hasKey $app "healthCheckExprs" >>
      healthCheckExprs: << toYaml $app.healthCheckExprs | nindent 8 >>
      <<- end >>
      <<- if hasKey $app "commonMetadata" >>
      commonMetadata: << toYaml $app.commonMetadata | nindent 8 >>
      <<- end >>
      <<- if hasKey $app "wait" >>
      wait: << $app.wait >>
      <<- end >>
      <<- if hasKey $app "force" >>
      force: << $app.force >>
      <<- end >>
      postBuild:
        substituteFrom:
          - kind: Secret
            name: cluster-secrets
        <<- if hasKey $app "substitute" >>
        substitute: << toYaml $app.substitute | nindent 10 >>
        <<- end >>
      patches:
        <<- if hasKey $app "patches" >><< toYaml $app.patches | nindent 8 >><< end >>
        - patch: |-
            apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            metadata:
              name: _
            spec:
              interval: 1h
              install:
                crds: CreateReplace
                strategy:
                  name: RetryOnFailure
              rollback:
                cleanupOnFail: true
                recreate: true
              upgrade:
                cleanupOnFail: true
                crds: CreateReplace
                strategy:
                  name: RemediateOnFailure
                remediation:
                  remediateLastFailure: true
                  retries: 2
          target:
            group: helm.toolkit.fluxcd.io
            kind: HelmRelease
    <<- end >>
