---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome
spec:
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/default/navidrome/app
  targetNamespace: default
