---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitcoin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bitcoin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        RPC_USER: "{{ .RPC_USER }}"
        RPC_PASSWORD: "{{ .RPC_PASSWORD }}"
        bitcoin.conf: |
          server=1
          listen=0
          testnet=1
          prune=1000
          txindex=0
          listenonion=0
          rpcworkqueue=64
          rpcauth={{ .RPCAUTH }}
          [test]
          rpcbind=127.0.0.1
  dataFrom:
    - extract:
        key: bitcoin
