---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: openebs-hostpath
