apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:1VS7T9JidhmxHesGFzxt9NYhEugSAnLDOSdjVAl+YyNOL3/hl+yfPmLyWfMJF3WooOMnTAU=,iv:ngjfSKROPqblpjE0Z6sZJQeKqvf1CgnoVn/vjeAOlfE=,tag:BpIUHACqtLolh7d26OwKWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcitMM2pkbkRYK2RNNmIw
        NmhkcEsvby9KWk1yZlNjUU00K0U5Q3hxZTBRCm9uWWlWTjl3NGJENVJHdlNLTHZO
        Sjd6VEwvMWpCUENBdkRkckpzc1dkN2sKLS0tIHRTbDdjNkxNdDVqa3RhSkFWZzFR
        MUVCOWQ3amZpWWQyNnI1TEFHQzRLdTgKFIr0LqL5Y9S4jkQMdphRHSwOvsUokiHe
        g0LsCSmfhuKtrVqBBPzWNJWW70duBVhndWyEHH/OvyHdo52vsbaMug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T15:31:05Z"
  mac: ENC[AES256_GCM,data:coz4TRyTJNvRTNo7NsC1rCm5nhPakZenyRLUhQkYBElk55tGepeLF+CQaRQfV0F4/UMu6p+jZ4vagGv6IH1u9olTAZ9ETrhos8ykCNrWK1kEPWrzIr7AHZvWzsGcUDP5tMru1ZNit2Y4cOQRa+WdMX+1IVoDMnIZKVEnWJHgs6Y=,iv:wRPz8aQxgxv7jgDuE8OcbUwk9UN54jOTdgK+Am+wXR8=,tag:nsPGwzFORVXITIVaxdH4RA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
