apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: network
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:uK0VOMHgnx8lv13zgXVOl9KbRIME2zr3ozyx2M0vTD9txButDybCPiCk6VY573oO8A4zVXOgoacGzaECTcxW/m8B4FY6TMeF3PD+Ow1tVJc0PUFljPgpa+ViqtCcxR70DFoxrJumxPn9ZcSq9k8OYYi32VuawlG0cb29Q9Outn+J80+0KQ8Z1pFPBQVdCzrZDJvafm3F/iWMg9bQPHGIQKSikce9fkByBVPtZDtRGqBV+1s3,iv:kpycwokQtibVJdybJtUcx6Tb033OBppMPfFwQUWNKB4=,tag:yFeU+BPwXxPJJKq7SR0VbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkpVNDhWTnlXb1ZKSFpN
        V0M0VWVuOXZkWHdib1YyWTZhOEQ0aU5tRm13ClVqSnNSa2FtZEZXQnhmT2x5R2g2
        SUY1Zmd1ZUlsVUtGVmtydHdnKzhJeFEKLS0tIHlvV294eXVwSk91Mm9JN2E3YTJP
        b091bG9qTHFCQzJwN0l2aTJQaW1ybkkKsiRkEyY9CQd8AolIhdUcXSBGoTe4BeZY
        EjRMcihIlYDoW/RLMUFRmaK3XA3W6AbJcReC7mVtbcy+whalDN92rQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T15:45:11Z"
  mac: ENC[AES256_GCM,data:TW7m4WQ3ZuYG0dcpv9UsxARx+bjC3W9N1939eFslFKuRkV7ydmd+fxpQYYSXSxaXbX4qGJmbvXl5hAWukM2NTvwCG/mggWswYyJOope8xEfKV+QK853O19pkB+vyOVGkfF7TMMz5Z40i3d0kH6b49VtB9MtcdJTo+GZ5kFrZ+u4=,iv:9piW4HX3Tl2/k5PKKh1xJwJVSs2UcFkNwSwrUcwewMA=,tag:OovWxPcxqI4dhszfW0NYqg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
