apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: network
stringData:
  api-token: ENC[AES256_GCM,data:p34LWSpQKjczGmQgefCiyCttH2ug+B/l4INWgPK2XWiGJHi0z0eNMNoiLJizaS8nMVi/vxk=,iv:Wi3W8zxljdTFg8PqKiHTdiKw9Zc7N1v2ByubSvRoyjI=,tag:mAnON8lhIsRjH7O2AFib8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya3A5YkplMUVESVhEQnJ0
        VXR6aEdGRUpWZ1MyNE4zNkdlUXY0cWVLRG0wCjBmQzB4RDRVeEpUazdYV2NuZFZw
        bTFPODJsTFNJQWUxcThSYXVucEVpYTgKLS0tIE0ybGFEeDVvTWhrRkRWOXVsbG1h
        RlFXMUphQnYrczR5OVJsaU04UUxWOUkKka1LkfdqwuzCyDjedLqG0uteGSLZ3QO/
        M9AKZdJeppD2eC9upP1ioKmV9A2O0u9Hn2+05j3ZTw5yF2XdBq+hRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T15:31:39Z"
  mac: ENC[AES256_GCM,data:MjNFOQkS/9Iv5pfZahXtF+FmJr6oJXUSJdNWR5am3MJF9lk5G7mS4WwY0pFRUIasdXosutOdtZyl4qHO3W18cP9e21E0m8+Yuc9LkugDfDoRPkAov0t3yiYSVYT7OAsLFPako4kRLQM7HS1pDFQRdKeca4qIQPxcdDhRpLh62pQ=,iv:GLqqR22PToCG1jWUC1XyRGNpd0n15vayifQQAS8Mb6w=,tag:3812oFtUFPy+0ZkScMkOAg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
