apiVersion: v1
kind: Secret
metadata:
  name: copyparty-secret
  namespace: default
stringData:
  accounts.conf: ENC[AES256_GCM,data:lEvYC0S9+PKv/mTRtmMQMCShLUyLxJkrKxg8Ssa9vIdHps0fQM571lvfOYWkkeybOqL9HUM=,iv:tN0NxIe/lo7bPnZQZ18fyn/Mw4ogGFuVzB9xvuUJaCA=,tag:v2gUdyT+skswEPhjybAM7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvczNRa3lrQlo4NXRuanE1
        YmFlY0tsQUxNWWhxWWlISVkxbGZhNytvbXgwCi9uejkvMy9yWEp2QkY5QmJiejNY
        YXFwdWM5VlZtTjdjVTdRUW0rVzFBOXMKLS0tIHJXTkkzYkxlQ3YwZ2ZZbi9pYWdV
        L3NSNlZ6blpLbkd1aEhVVkt2RUE5WjAKUHnBXLmdZbR8HjHoi+FhV4o87UfJOAdu
        1sE71xNzRFOVgOX+/amGQORYySRq25UmD4speSBpg6ZLH97HH/Bw+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T19:59:20Z"
  mac: ENC[AES256_GCM,data:wUMfDNd3IguAiWYUK/kHgARoqqVJ063s9O1CIkJ8ND6zksESilPsnzaIzfRndXDQGtvcuIbyMmF5CF53OkuIjv0ypjyTNVzNH1Kq+kD5HcllwKXID8gaQoIm+mZ7MV3dGcL+uADklafUUFx2rmSC4efWy33cSFoTTnXNrIPFBpA=,iv:aF0VfQZRqP+SsNR5cIGY9U7cL4DMDARkBpDCFDpf1as=,tag:kZWQ0Z8sku6fJc4duB2gBg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
