apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:ka4d23NN9h6F3FuCdx5yYS2H/osYUC11G72AaXkVY14A62vvsU+TeRe4I+Sc1o43Ia4mn6hg0YfT22XJrc83DQ==,iv:fP/kawn9WISh8gcsFDT8V/wCwxt/r9m1r1vy/wn/VhI=,tag:dz9FeO+OxAo4oxofTyNieA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVjdxdG5wVUxZVWs3QWRF
        dTIzbGRMSW8ybktRQjBDVUIrbFI2ZS9jY3o0CmdoSDdzYUZzN1VUMHR5MzJZeVZL
        M3ZFYXR1VXAzSDhEWmZ5MnI0MnlKUU0KLS0tIHVScVRkUmsrc0REb3NscEM3bkhF
        ZHlFVjZiaEZqRUVxeklRR3hCaUNVOFkKlzaq7aoMDy49olCjv1jTJy1r4a3Nh+Kb
        c3EdYXs03Cp5VpfU23VV5EVYi6BJr9YgPcG5tIU4Cz4k94oRrCZt0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T15:48:44Z"
  mac: ENC[AES256_GCM,data:Uc/dGflkO/Jx2HFGSMPj2+vPitz8hk5gbmO1oZxs9WgYXlCgBc5zQCP6vNo3g5VeyG5bnmEL+9i9EYa8PmlQ/X2ra+S5/ePmCWkRHLvUqUsOo0bgjbXlu7SjAPs/TTh7jVWTFclb8JmGY1s0KmgIHHpvs3lrRwLjCuuIpcGwFnY=,iv:YyClxTQE9ZNprEyLe5HKPKGsRgJ3sjMwipRe981v50k=,tag:zIpAOeKIudDEPgRNVMuOhA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
