---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager-secret.sops.yaml
  - ./cloudflare-dns-secret.sops.yaml
  - ./cloudflare-tunnel-secret.sops.yaml
  - ./cluster-secrets.sops.yaml
  - ./copyparty-secret.sops.yaml
  - ./discogs-watchlist-secret.sops.yaml
  - ./forgejo-workspace-auth.sops.yaml
  - ./github-webhook-token-secret.sops.yaml
  - ./onepassword.sops.yaml
  - ./qbittorrent-secret.sops.yaml
