apiVersion: v1
kind: Secret
metadata:
  name: podinfo-gitlab-auth
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:Oi7WRyf1DisKzO4w0tf+Css9CbJhsMxtFBXbHrU6mIZEiZu+rf5geczFzBSmgFz8m5d5a+c4VYEejUFiS7VhgHk15Dp+mhtsQ5dA40yjKlnL4GN2GR2ZqsREDZaICGodXxLnsCID1/LqRULWPSj7chOb2XuYBu0d4lipgsy0f2gOcN3mo3LcG7MKUooxzjx0U4i94nCunEdNBiT4110C9mSxzVOA+KweAHFRBpHki/gAYLYgaMO76YJ0fEp7XChuEigJNfbGBdWqODQLL+ltttgxYccTjiU99x2KdjqYOhzvFH73bhqifg0BDN30+5JAviHscwyimaNxhgONb7nvzDmIdgSZdNPuiEM5QTns+l5L5J6vGljr4nwbGeTvlYjIcMz8Cxx9Gr8sHmnWxTJy6HgZJsYgPikSqq/neVIrnUDwHi+ODN1OAVY32bVvuBfliBHxLP7i1NJfcz9k2rboh8lhjZ+VMeeCfzFF3LtTBiPbzm2QhW/1PSwyD8Sx4bAQaglqL0EC5sNPANPN034LoTo+7e51sFz4rBj8,iv:vAs34juRKVfi7BEMDW8OyCXc0m4NqRth8GS4HGiNvRE=,tag:pYYlxYH4srv54I68OJCKMQ==,type:str]
  identity.pub: ENC[AES256_GCM,data:v0Bi+Rq2FmN62UwikP9z8k3IC/az8aKyRiWGpGRVg3cQqf0sFRcnFNnpNje6ZTwiRO5TM4de4eCXk0iPOLtwqx3AY3+4UkF7RjocUJ7GSbqKUH+rHdoCEC+v+yLXK00zn6Mcnp4=,iv:b8IUYCR1AliGRCF7Hp9tGE9oy2UI/NXoRN2vEO7UV6o=,tag:1TFN3YqRh4C9h63tU8DxMg==,type:str]
  known_hosts: ENC[AES256_GCM,data:DanjUhi8GB5d9KHF0uc/or5uIBUrs0sTRIgvjYriW3D7fg6PJ/W92YrpOZfzFCGvFl8kvkfvPGUrzMa6r1wxZ7pUjUWNAXoGGJ4/6TOGtJ3/sWV86JAH9YT5P9xAIDQ6pnNwXqACT41GBe0UhAUdKGcqFA5blddpm/Cg1UjQ+DODH1nPTIu372pKVni7C34TqKL0Zro/iSYvkmJWZ/5EKUY7aJ4Jz0UAvxnkuzu2AJ/1ZPNFZHBHNDQx3RIq10H4xeE+rUs7/JxQJOkLNo2vH+2UqIZ4au3Xa9wSyrGzU1ppsq9TTkVz8ERBh1hjCWOT/BEfxyCh18pXMUxLCpKA+aWhcWV1O3pLwsGczHHbPwbFnJe6jHI6yCYlFRq6YHbTLOPTgYBJlSVZtUMTe+7NYlEiK+y5GNLsOaSh6qwTyqmlVLLsoZmT69ScUBPTrbqyJa1ML9iYRicTSVUKzjfMKf2OBzs4PPh0EbtPC9dRW2ZGmWc1oW7f91XNUq1XNZFt/NFliBQCiRMOleCsuz7vwtW7QfEWqWWqsYw8e/wJ93UKqOm7fG/KnRGxvdJk5b7YuvFBLyFffZqyGakGIuJtvMrPkpJ/7ccg67lMXv1e/Vs+dFOYDAdHANYBBbhD/LaID0cdfQ==,iv:YN+BpTqiXg7tm+AQnyy+n3Wk7rwHI3J+HLFZqglYS2E=,tag:XIaCYOs23yNgcjzZuwG80Q==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RXZYb3ZNdmpqR0xRdEZH
        UWFyd2dFQXM3V0FkNGdiYTZhZ0QwWFMwYkNnCkFlamxVRXRWa1BtcGpUNzlnMEtX
        Q00xYVJ6RnFrODJPQ25lU29OUVFaOTgKLS0tIHYzR2tOTVVqaUNKNkk0NEhLYXVI
        dzlkOG1Vdi9QQmdUZEVIYWIrOE9BZkkK5WWeokSlq3Q7cDEJATGo8b60rj3+W0V/
        o8N0rekFFPEqb7nfTwbuuHOn9kD7xF5jN3NWC3eBFJ1gpMSh5l20mQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-19T10:18:12Z"
  mac: ENC[AES256_GCM,data:QvGJTsPAboQbStubSCeUyKg0IR+W7i0Hv6CXApX6wdoySK0J/nHHnawgyr3Eycmpkj8ti/4v9nnIIGCcvL9g+qxgjrikLsBJs0JuTgv++W+zR0FSNGbqBUXyIRza8sQJ610q6qNlWZZftuW73P1Fbt191rJF74piR5ZUKook+0E=,iv:t6GeesqY1rTF9m6bjv+DpPYv+iHI11Q+ffhT7UL3gGc=,tag:03svjtHVnUyWAEend83Gcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
