apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:/zZ01w/AgC3XTKetkjKtxWIHrtiLTWRONfoS5SeazGE7CYNUPcaiFw==,iv:C1+Z0a+8BL4mbtaSPpvNxImZpHedu5+/uPVrrb1vaK0=,tag:LBI8dP882QepIgwJMZzaTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySjI2YW9TRzV2OTB2Y1dH
        UjZ1dmkvRlFIYXVlQjBjOHFCVURNc1c3bWdnClUyaTJGTDFvbUx6dkNNMk5nRUVw
        Lzk1NUN2Wlo2VDB5S1Avcm9OOFAxSWcKLS0tIDZtdGlaUHpZMmE2d2lYbm5QYlY0
        V0E2UlZVQWEzTVRwQVU3ZXNRYlhWd3MKOeOUqdcco6IlfFXB5ylM98drrynWZntk
        eFgzo/G/zljIQwIKRYzJfA2NGuIhXXxKvkcItbAuqzoNwkhfA5HVIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN1dscWU3bVhtOFJJS2pQ
        RzB6V29EUkYrS1dNWHNPY2dhRjAwQ2Jyd1hVCk9vMklkT2xvTUZCRWsxR1pENE1K
        VVh5Rk5OUG1SSUI0UE4vSVV3Qno2UjQKLS0tIGpUbG1SR0ZCTHhCUlhPT0dTZjBL
        a2dkN04xYnJ0MVhJS3A4dWtjd3AvU1kKldFMow8nmtNGUXUIPLkWIX0ZloR0OCcy
        S1TxWq88INTspq9WXz0Pn0b+VFyri02+cGUROEyb+Erhtb+SKlN11A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-01T10:24:01Z"
  mac: ENC[AES256_GCM,data:1/A1C6EYD72YAG84GRf2RvjdlrcNjyh9QNnnO9wxQ29/MW2HJOPl/tjwHGFNWn5/oUTNOA1L2ymzs6P5nbYnWlrhESC2xfeE4NzPUsaIkQ2fAEMS0rXs1KHJr7399C9e9GsSfY3+C6bz4roOohNnls73tN2qe4j2A1kFSzKuTHc=,iv:WfIzuJqrPk/L58ksPY3zAGVNQRy2VjfdFZSB6E7xQ80=,tag:WJjEsX3B4pLLu2aTSfZ46w==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
