apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:/zZ01w/AgC3XTKetkjKtxWIHrtiLTWRONfoS5SeazGE7CYNUPcaiFw==,iv:C1+Z0a+8BL4mbtaSPpvNxImZpHedu5+/uPVrrb1vaK0=,tag:LBI8dP882QepIgwJMZzaTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdnA0ekgyc1lMbjdFRkpZ
        MGFSOGtHd0Y0VUp2czV6dnRMM1ZOQ3JTSVUwCmloSmlSWC9PSlBnb0JERlVmUVM3
        WHdESlZ0djh3dG4rTG8wTTZ1MzNTNWsKLS0tIFZKdlY3bWhIeW1EcTJXUWxMWUwv
        RW1rVURYZlhCWGlHTHBvMVQreVBFbUkKiXao+X1DVYDmymJWchrrdIHHVwbSPJ02
        yq4UyTe0vO4jLFpMcsFRQv29/F9EMHMTrm9YtGYkcPl3bXo4/7aIbg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-01T10:24:01Z"
  mac: ENC[AES256_GCM,data:1/A1C6EYD72YAG84GRf2RvjdlrcNjyh9QNnnO9wxQ29/MW2HJOPl/tjwHGFNWn5/oUTNOA1L2ymzs6P5nbYnWlrhESC2xfeE4NzPUsaIkQ2fAEMS0rXs1KHJr7399C9e9GsSfY3+C6bz4roOohNnls73tN2qe4j2A1kFSzKuTHc=,iv:WfIzuJqrPk/L58ksPY3zAGVNQRy2VjfdFZSB6E7xQ80=,tag:WJjEsX3B4pLLu2aTSfZ46w==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
