apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: network
stringData:
  api-token: ENC[AES256_GCM,data:mBRSYIYUok6cLiyevkWjOeb4dts98mNOLfoe+h80Dn5neDaBq8hypA==,iv:wqIJ4HWeVL9S2jbJCNaCF6HDi21uDu/x0xy9DChuV54=,tag:KY1vbKdgP/NTKGgfKRszrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYkk3UUFHaUZwVy93RTNT
        VWhvTmtReFExdUJCaHJSUGVxOFYraWc5M3hNCnhrRFdTMTd5RkRYL1BPL3JBNkQ2
        K1QwVnMrSlcvaUdsMnlxUG1KbVI0Sk0KLS0tIGdWdStZWmJuaDRVWlN0c3RxVWZF
        K2VnT0lFTGFSd0NXZm9hemNCY0oxbTAKK8RDKJiOJnm+oFOs6bwLcjZJxmin0it0
        B/hXKR1twPZ5jPVQeij80NFnN04hQp/n4WNg1NtwgwWHDsAIPu4Jrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d1VHa0VxZVlMVStFZ2di
        OVFRajltRm1vTWtkQWRWWnpsMVZUSkJJR0hzCjF2QW9CYmQ1NFJxTHJwUU9zUDI1
        Z0MrQ1RrZDBlREh5WThHN0Q2T0ppWjAKLS0tIGIyR2xYOTJVcmcvTTJqVkE1VTNC
        WVkxVE5VTGV0Z3Q0QTZqT0hwUmZ3djQKva2UgEAC1vtdS3md87fV8KUcmw4UmdE2
        0rgw6hJA6X4ZAO08s8PAndRl/7LOrT1CoyVhSnv2a0aYNlyKKP2pmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-01T10:24:01Z"
  mac: ENC[AES256_GCM,data:/E743qUsp9cSGmwxJGZM1XBUmgavDdulu5dA7AHStMUchH5GSYg1Qob2C7hAKnfzihN2Ydxc0XUUShsmzuH6saFXW4rxUuETgsKi5CqE9/OYIkjY3pNvDS3Cvzt4EFpwwxdXyG1iQfuWsBc5W41A2n6+luOA8ZZm9VoTrcfZzN0=,iv:c9m8EcI/QFXY2qpoYUQl5J1l7oJepjtAzMptNQuDhi0=,tag:nHpb7NnQTgFm7GhvuY3EUg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
