apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:aMuEbVFku8ujDRO0xWbN,iv:V4JocuPf0WnsY2cBPomN75wDPg5mGD3bSuwF76ICx1A=,tag:GmV4O3icGyfllKcdyveQCQ==,type:comment]
  TZ: ENC[AES256_GCM,data:GLe27ZQ4B4t1LC4s5g==,iv:nZ6ZKQpsbfwZedc9qz+YA9DobXwQwgp1cRIg05QfNSU=,tag:/dq7wpDfbownUUgrXD7anw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZD9Gag/4UTNC9Z66,iv:N2wq9mtOOzzMlgYq8Fni4dkEux6n8aGd2jy5oYd27pM=,tag:Vvsz0uYecjCE6lOqfCnVlQ==,type:str]
  #ENC[AES256_GCM,data:WV/L+ZVlTwqC3HvM,iv:hyfejp4ckpOhrks4aAYrt7jihRVZX/8hvNOdlu2NnII=,tag:hF/+KESjfWdosjIjoCPY/g==,type:comment]
  CLUSTER_POD_CIDR: ENC[AES256_GCM,data:nnywS3owOLp/4Jub,iv:OZdX0NIu8f2leM7mdYvm4Gwyo/+XrIIIne4YiUhl7Ak=,tag:L/Yd3p82W6nHmDPcghF8CA==,type:str]
  CLUSTER_API_PORT: ENC[AES256_GCM,data:9sBb8Q==,iv:XMreO9+HG3r9aLjFnW/VDnViyeWH2AXN5Q8EHyRkIwc=,tag:G+B5C2AhdXYqoJ4rOh7qFA==,type:str]
  LB_POOL_CIDR: ENC[AES256_GCM,data:0Arz0NgknZkcF3N8,iv:mM3sjxCFjMQn0uSoN4v2BNNiQhhSVrls/WxEK8Jwfwg=,tag:+f1AxOkl2oHjHKa7VWtLTA==,type:str]
  K8S_GATEWAY_LB: ENC[AES256_GCM,data:KqL/pSLNlCYSObQ=,iv:pUXZ+oSIye0TRMagW9Ka4+gS2721gu03Kp+btFht7LQ=,tag:+8BNzoKLFqWBaEQihnG8nA==,type:str]
  ENVOY_EXTERNAL_LB: ENC[AES256_GCM,data:lHG0oCX62IPzEc8=,iv:ljz5gXmDJyUfi98yg8Jb+ikI4HJ6tYnjuLoX+xHRJk0=,tag:2dgAxdGBdKrC5IPiaRrRqg==,type:str]
  ENVOY_INTERNAL_LB: ENC[AES256_GCM,data:k+Z/plpiHogAONY=,iv:z8ZQ1UArrwi8QZWnaGk/o46IH5NyDaX+ZpSUqI5n/zk=,tag:5uRDvWml6DfhJFUKvJddbw==,type:str]
  SMTP_RELAY_LB: ENC[AES256_GCM,data:iCGygBYTMNuskK4=,iv:+W7TprsEO1UW6HwaT7mwPPTFPlfEiSOjp/lt5noZFBQ=,tag:eOYGZ9mnDLzb3ceDohOS1A==,type:str]
  CRUNCHY_LB_POSTGRES: ENC[AES256_GCM,data:SOR6HHSzgFekXhk=,iv:HFA6qJzmXJmk1GrZMw3aeGagZoRg7BQ604dgaBXsZ3U=,tag:luXJIMTxcN5gmulnv+GVWg==,type:str]
  SYNCTHING_LB: ENC[AES256_GCM,data:O3CZb2BGprJF/QA=,iv:feT4bHxQQ/VQzdtDiPFnqc0dEM/ZNDfcON/xVAXh67Q=,tag:u1UIDfS2VU/yara8+WJMZQ==,type:str]
  JELLYFIN_LB: ENC[AES256_GCM,data:hgMAHb4n1TUPKR8=,iv:rkM7l7qRj17qeijfDsD9LEYnpG8QRL0Fu/PLynKVwlE=,tag:iu1tb1RaPxUoHRBOPIVi6g==,type:str]
  S3_SERVER_IP: ENC[AES256_GCM,data:NkIkaAkMQur1MQ==,iv:3UQhu5TGWnQazkKWEVmFMPe4Iezqr3CNoTK1sS1e0r0=,tag:xmw2CIzHetErb7RZQTtyTg==,type:str]
  UNIFI_IP: ENC[AES256_GCM,data:7JH4BwISgVhi,iv:Wc9lUP+u/Nm9o0qespeP6YxgD1RvmrJWeWepqnN9mUY=,tag:R3FSddx8pNqBMJSz7gXGMA==,type:str]
  #ENC[AES256_GCM,data:nflHIIXrLG1LWhl7,iv:0seXD9kPO3WD/tVtD6oLpZXD1C0ecxquzuiEvYS0iQo=,tag:Nl3M6+EqubfKZlPgXx2A1g==,type:comment]
  REBOST_IP: ENC[AES256_GCM,data:/CA7cNAGn49v6A==,iv:cd58rNCgaiGIdXA1B38kwqTrtf+z2ZUgUOi90aBGImg=,tag:S4PuyxLETqwXM8Vt7zGT4g==,type:str]
  REBOST_MEDIA_PATH: ENC[AES256_GCM,data:fq6x7FI=,iv:YrnkwUNGX04ssbjcU0NMb5EFn/e5w94NASGV7BVjD9A=,tag:p2jcz3cIrCCUqESuI+7MZw==,type:str]
  #ENC[AES256_GCM,data:xHtiHF9X8X3DB8yVya5E5nCm9RY=,iv:TuVMwAREolcMiQ4aJc3qwhLhwbT56nZUeFgr7Bp+FGQ=,tag:vk4G3axlSgxq/wLEHmAIcg==,type:comment]
  OP_VAULT: ENC[AES256_GCM,data:mG8R4ETwUw==,iv:sXlbwlMjfiksVX9YiRPv7sbWS4fwtPmcMvs9nqX46LM=,tag:WNkAIO5M5azJOl10Eujg+Q==,type:str]
  #ENC[AES256_GCM,data:H3D1LvjiQD7FaTphi5tr,iv:ozTui23knRVbOJ8fgvExNLc+ds+WMdK0uD+f5kx7ROw=,tag:hbu8yjFK0EmQQJ/4I2jUCQ==,type:comment]
  SECRET_LDAP_USER: ENC[AES256_GCM,data:iYJR1FUvmGyy2n6i,iv:j1fwqmq9mJo+7SDx3+d2kfCFZJ9STyVl5Jm4tdK/YNQ=,tag:Zr+3kwFhWETOlxyfkKdWrg==,type:str]
  SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:gJN4gMD1svEu4mrjaNyC,iv:xtahddTcvwcsaez+nmTTHuTPKnTiLXFrlo1nOV/SBKM=,tag:srQ7qvSxLX4u4h0/DUMQnA==,type:str]
  KANIDM_ADMIN_MAIL: ENC[AES256_GCM,data:pj5miburAlzhX5dW5UH8nkNyTA==,iv:tDT4Y7uzVvApOcPn8Mdg0tJXMrWjj7MsbX91Oea58P8=,tag:dMndfkmCVCqTeQvFNMB1iA==,type:str]
  KANIDM_ADMIN_DISPLAYNAME: ENC[AES256_GCM,data:8tH37Uo=,iv:FLFk2ulEGRcpG8CawUme7BG7EncgWL14FD/haGmnc3k=,tag:SFu7rNT3ErRQDSkdlSM7eA==,type:str]
  #ENC[AES256_GCM,data:2ICSICBr/73oGfr3aw==,iv:tBfv/tq47MG6RZ5xv4aPg4LmBaSRRGBIkd8kx8sFi80=,tag:zJ+cu3J+HK4wdapR1VqaAQ==,type:comment]
  OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:HVW8F9xTBTJpRK7NSuE8L6XVvtbh9sRKnfAvYmqWosyED/ZffIzVHFH7J5aAbJIsPPe2Aa7UM0IdFH5J65oBkg==,iv:9FPtov8Zf+yOrlknXU1QR8sJeoLhCl42S2faHu9v61c=,tag:GHaZs9gNWEPiHQvSnUNYLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK2Zmek9qY1B4WEFWQ2pG
        YkM2czJuYjZkOU1CYWRSQXo0UHBtSUJVaTNFCktxNUkrd1dlNkpxYjFNb2o1azdi
        bGV6amt0RjlkOHBJY0FieFFweXNGem8KLS0tIDZvdzY1RThSNFgrMlBFQVQ5RFhi
        MzFwN2Rva3NkVHNabksyQTVKRXJQMUEKPZR+Lll7mH29zBryR7Bqa7rJNj2Ny2wH
        SOwiRknmAnJtAqkfeliLSUb4QaBlaVBREWP6Kl3KpnoPjNKyE3p3QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T17:34:08Z"
  mac: ENC[AES256_GCM,data:z7orR+59uZWKlJ3Tv5Td8Nt+pz08CyGqTBL+gXcaOyN77Xy5I0+/PJgqhiPp6+QPx6uzoEV/GpaqAcVxKDmdQoceBF4XDWJuTTKc1dU62yPiUIeyOPTW46xNGc8Gv3ugrt1zRlbdfMwUgUCEiypCu4eJj2k+zckwfTD4WzmGb7g=,iv:M6LMYUev4VUaT1C8EaCTKSLdwNa6XAVZJ9K7pwflL/s=,tag:rnfpasa0V7xvbQvHwxAvKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
