apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:5W4K/uZncOkeDHMEPuJp,iv:LpXDmpQ9aueMm1eHc+CSW3lhqIlo8bEVyMgGhiIKugs=,tag:0Q0jU/DrRC7OADCJx9jUJQ==,type:comment]
  TZ: ENC[AES256_GCM,data:l/FDVvV0NCCivToOPg==,iv:F1dh5MW62hwWJWPWzLfmD7Rct7Rq/xeLbm8DkYNCj3A=,tag:sbNN/2lG3g1b5DgSn6zrrg==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:TGUbJtMcXniMXZvd,iv:qj7taY7VVF93+XM1U6Bdp9QSYtLrHZw+SQGdItfYsv8=,tag:Ys4w8KyIBhpcN7Kz34xUHA==,type:str]
  #ENC[AES256_GCM,data:cidLyPcUKENZsYYa,iv:KilMP0jv73mHymCJbJoJU3ijNfgUqQ429FX14kWTBVg=,tag:SFI933pqFuQNzVMJ00kjBA==,type:comment]
  CLUSTER_POD_CIDR: ENC[AES256_GCM,data:VBtY2qNieXWpkgl9,iv:Q5PqoCNUckGfCFj1/EOAs1W2nFSRlfo9n0/RysMmClU=,tag:ODE3ucVGlua6JUD7vCJpjg==,type:str]
  CLUSTER_API_PORT: ENC[AES256_GCM,data:gi5ydw==,iv:ZgzNFye36MUQb+Ewv/VKG6/IWLcQxs0fwuh9toWVzPg=,tag:C88HXsWhSOjRhLKwrJXXYA==,type:str]
  LB_POOL_CIDR: ENC[AES256_GCM,data:t4cKQQuu0DpQGDBL,iv:oARZ0UQp4pMJdl5+u71lDtdMT52l4o3I3NwtZuOQLzU=,tag:R1lSJh1MpCn49hPVHYbN2A==,type:str]
  K8S_GATEWAY_LB: ENC[AES256_GCM,data:FYf6gXKC1uRfUFw=,iv:7VsUiBo53ExFnfXSwrdTEm8ERDCdouwwV6b3lsBVLK8=,tag:+Yvi3CUftev6xR/NHi6QEQ==,type:str]
  ENVOY_EXTERNAL_LB: ENC[AES256_GCM,data:49evnfAIUe7Hb3U=,iv:YrEphoVZ/+xPP3Cmz1tRB5WblrFdx+ry7nSN0UFviHE=,tag:E9Hky+LI47p6rKnX6n1vOw==,type:str]
  ENVOY_INTERNAL_LB: ENC[AES256_GCM,data:nszBemEe9Sz7aRk=,iv:beRse4dqsobNZbvcbBeeQLv1uGB9O46l/vgJxoJ6oZk=,tag:49rkQ/aFL9XCbV/I66C4ew==,type:str]
  SMTP_RELAY_LB: ENC[AES256_GCM,data:P59To2ZynCuaeYw=,iv:OhGBVsU06ZACjl577AjZRJRFw92iETK9KrON3ubqZQw=,tag:bnREpHqG4mYYJoH8uwrPyg==,type:str]
  CRUNCHY_LB_POSTGRES: ENC[AES256_GCM,data:s66+Sv85jc/tajs=,iv:Du/upq/VOkgFpZx3PDWTS+XsABxIMudWM2mRCTi5vv0=,tag:O8yO7pwXpRWeVWD9p2TM0g==,type:str]
  SYNCTHING_LB: ENC[AES256_GCM,data:EzLawmd+VJQ8nf8=,iv:1B+dYFIx/jxtqM/eCM3rzrbupMVCZ+h6cKmB3/VVMsE=,tag:JuTAgFN9FcIci1SMy2eyVg==,type:str]
  JELLYFIN_LB: ENC[AES256_GCM,data:zWJ9dOV9NGBINd8=,iv:xL21FEdEh3DcEpB5gM8dLG/D3M9hq66kgTJiBJOIFgc=,tag:u4TRVUIKJ1CH4908seHsmQ==,type:str]
  S3_SERVER_IP: ENC[AES256_GCM,data:G2abvsiVKtDUqA==,iv:EZo+CoLojEhMTu+IjiTyDs5Zw/AO5QHYEfhYwa3aKtI=,tag:lSc7k0nawsmktxzWpuSZqw==,type:str]
  UNIFI_IP: ENC[AES256_GCM,data:6Ll7uQwelFRM,iv:SmZzTPRjaUMpkvTJo2O3vWsFuT/KBBDtaEFZ3ir8/qQ=,tag:f49MY0ijzLwTwAW67OkA3w==,type:str]
  #ENC[AES256_GCM,data:DY6hpZZgLyL08couuzN9uQ==,iv:Sg/EhwNGpZVOOEXwkaVlTp08Fw+FozZbnTT1UgDHHjA=,tag:rY54jxbQ+iKCTQvmgRDAVg==,type:comment]
  STORAGE_CLASS: ENC[AES256_GCM,data:l0DWcJqz4e+1hGuiW82tgg==,iv:C7h8pBm2fkpyAfYJoK106iwCDXE9rbf4BRToKtzKkDI=,tag:rTvpNJwjgb2/VEaq7zh+XQ==,type:str]
  #ENC[AES256_GCM,data:VjTr2ru842Q1WZyy,iv:t2M+83IaQF0WJC2VfhQkv+/lhxPOEfXwaJ004fO2+kw=,tag:wuXwYlE6ZMFX2ftYU7t1Xw==,type:comment]
  REBOST_IP: ENC[AES256_GCM,data:qLMyCrrAlvOrEw==,iv:xagdnkwFYzVs1PkrkYo9j0owJOvFpj+ntilaaz87RsQ=,tag:QRoMBfrc2TGOdRLkESSJ3g==,type:str]
  REBOST_MEDIA_PATH: ENC[AES256_GCM,data:BjbafGQ=,iv:DbdljU3ohbj8s5MjuorD8CPGerNyyVo4Ref9OvoqupA=,tag:bcKfJkbN9FWgfTny40rgXg==,type:str]
  #ENC[AES256_GCM,data:qD3dtaTMz11u/mmC/ErsH/CHYM0=,iv:WOkz32cVArDa42l4HEd0xTXLpTJSVv4xhqFL3p3OX0U=,tag:r+7k4F41iWx4VCoOlPWobw==,type:comment]
  OP_VAULT: ENC[AES256_GCM,data:j6ybwy/j1g==,iv:Ta7ETdB3nuxDULTRXSVORZ2J2wWwBiVTozbyrZT7TsM=,tag:g/H78H3l6P1bisKmaAVjDg==,type:str]
  #ENC[AES256_GCM,data:RJhP7TZQGT35UpALOn4w,iv:AG7T2lyrpAZnMlzUSKlS/WWZbfOzD1Jfv9kTqJk1X3s=,tag:ZBVBcCm4U12bQIc/2tQFnA==,type:comment]
  SECRET_LDAP_USER: ENC[AES256_GCM,data:cVbQvtXFFDHOxLrl,iv:C0LCqxiliUfDg1BjOJxhzOmuP1hafKeBNbFSwhk1Y5A=,tag:9K9kvDGK9T7LQmW4M8Nn/Q==,type:str]
  SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:4vzFSSMzmN/NdA8teg08,iv:szGBI8icvnQLFVR3izcY25B14OmGep0dhSn6PX3xB2Y=,tag:mhpftZCD9jIV5co0kXJeFg==,type:str]
  KANIDM_ADMIN_MAIL: ENC[AES256_GCM,data:xaH0r8ldbE6BK2QPqaPYoVpUpQ==,iv:h3d7zKjsUhf0DOl9LCXsEmcXjW1IXTFVk2HWqDppy0w=,tag:SrM9iDjLcpJUwqXXTfvboQ==,type:str]
  KANIDM_ADMIN_DISPLAYNAME: ENC[AES256_GCM,data:1Yo3Aj0=,iv:lNKzBcHP1pEl5a+wbr8R/dO9h5st/Vbd4JnmqQaKsKY=,tag:NnhyRdy7Y8EqJ+BuURYxOw==,type:str]
  #ENC[AES256_GCM,data:ww7JgSE2w9martQcIA==,iv:JlrW660/szJ0H8j1g92UTbFR1rOiiHGaAPOFZtnA2lI=,tag:9QjDaEbSVJ+3LGJozwy2Mg==,type:comment]
  OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pAUKo/30oc5cfQa7u95536hUj1cGiQmSpD+l6LthzgWuO/F2jPAeI6wWiAuTc1L1KLz3DvkAjVln7YmeIPoqFg==,iv:DnHVEtGzuKgdpAZT7+jkRKXv7eJwNA3/aF2i1QhAsHA=,tag:WuJ851Wp6BzDT4OHas0yvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU0VHN1lQQXZIOGdkcXl2
        L1czRmJ0bmhnckY4UExUVW95T05uaHpmc0ZRCm1PQW1rWTNyZHUwVVI2QnBLMnRJ
        YVIwR0xBQkhQUjM0N0JPcU1jN2E2eHcKLS0tIEZXUTBzVGZEbHN5NW81SXFEVUY2
        YXFMQk0vRlVSdEZSRWNHWkVQZW5jY1kKtFlbAp3419kRNNXAFnx/+U8UeNk+JPzt
        GMsmoW/anXyTU7bhr2iVZiM5DzOraJ7DrqCLUSs8I0YFo+iEmZQiDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T18:53:47Z"
  mac: ENC[AES256_GCM,data:1H/z71oqLP2nXSZXWfywFYrSSycgFOeA74i+nlU782kSu6dnb+CsmuYRfmKojW5TSPZoxYQRgirAwujCRIYqDWZ8RjIvOCPLNQd1HH5oL+3Epo03ceSj3FwfCjY9PJ5itYfel+evk1j4aNsKVuGH4+mA88Pk4jVFgEvobk5pvRI=,iv:ao7KMvzl+50bO9OILdHOqrVEs4VBxbLH8acn+mFwib0=,tag:cxRjXVxE++lUcirf9aZALg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
