apiVersion: v1
kind: Secret
metadata:
  name: copyparty-secret
  namespace: default
stringData:
  accounts.conf: ENC[AES256_GCM,data:lEvYC0S9+PKv/mTRtmMQMCShLUyLxJkrKxg8Ssa9vIdHps0fQM571lvfOYWkkeybOqL9HUM=,iv:tN0NxIe/lo7bPnZQZ18fyn/Mw4ogGFuVzB9xvuUJaCA=,tag:v2gUdyT+skswEPhjybAM7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aHVVZnI4d3czQWNWZ1Iy
        bHRYcmkyaHN2RCszRWhRQ0QyaVhiZXhsbEd3CkNTVXo0UjVtSHJyRTJOOVRCWk5W
        Qks0VWZKSzBUOTkrWnVBUGpWUXV6OWsKLS0tIHV6bE1pazZhVUtBcEdOV2pBUUpS
        dm8rVHoxWGJobDRUbERQSkhkWDFHVlUKa7FSR1zO0qJQ7rdMJMJjVdU0PxAvfC4d
        /ve3uVXzkCGBcCLohxhp5siKuYOvHV0o1Z6IuIjrs2deJlnB2HQo8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUHBsQ2k1QTY5M0VlVVhr
        bnVWTUlIUmNnTFpJOVQ0NU5uOFJqWDF1MENRCnQrR0k3R0pWd04wOW95aXdFRG9L
        NTdBQzd0aWNtSlZSNDhvNFFsOTdDZ2MKLS0tIERXbW5YTElIQzJiL08xM1dONGxH
        QkorTk5jNStBekN1QlFOMi8rSzA4UkkKh7icryinJNiHeM8dSE4O3SqYdg8p+AES
        iEOY/DirlTO7TDd0Vnubvig7NuSdROVy7wWjloRS2KP6pQms5j7lsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T19:59:20Z"
  mac: ENC[AES256_GCM,data:wUMfDNd3IguAiWYUK/kHgARoqqVJ063s9O1CIkJ8ND6zksESilPsnzaIzfRndXDQGtvcuIbyMmF5CF53OkuIjv0ypjyTNVzNH1Kq+kD5HcllwKXID8gaQoIm+mZ7MV3dGcL+uADklafUUFx2rmSC4efWy33cSFoTTnXNrIPFBpA=,iv:aF0VfQZRqP+SsNR5cIGY9U7cL4DMDARkBpDCFDpf1as=,tag:kZWQ0Z8sku6fJc4duB2gBg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
