apiVersion: v1
kind: Secret
metadata:
  name: forgejo-workspace-auth
  namespace: develop
stringData:
  identity: ENC[AES256_GCM,data:RhvXUPKHQGmh5m1I4f/sq4qbBPaypLuQ1tQsTIr7O9WGO8bAc5iLC6RvE5YhnlaA/xGynWq3f4pwuSl0xwz73YzRtCtyCSjB0XlNAwohh6ZzzxJdQA6lXD5ao9EpngPAEIQhS/jMImIizBLEzbMHHhMQkdW3wPC348qeiQcyD7Y4m8zMeNDritpn/PwFskcQ3lPL3Lp2wNCW5wTwuyIo9i3b0UlxSsqLsOtgFFQPZdbkcuXiBl8yiSqBVyFHCFtluTl4diJk3HPl7OuIKUtuZ9vDF47771hBUN9aw3Ilc3qgjmVw1vOV4H2mPUqYw9keJa/cOaJoA71jCZLh4PEvV8LH2TX+Kqyj2fic7RKP8NBEiXTT9Hn7fNAuh2+w4zTZstPAHjAnUgd6oqvzLsA94TUVD7oAmkfoT3SYqvejGM/R69vwoqbwuywNNI6R7EQaX059OGsLKu28brkEqWxtp6LFI4uXS7akKhVKmsrtUA43Y/nPcxOrFEg+n0noz4HgErCg3ZB58pC+WE7AmBdwZynw1n8AHCUy7KNU,iv:uGOhkCdW9IQbWHLZYhgIzBTwOk1zaEZ7FKMYMwSr24g=,tag:bsKWEFYlaDnUxCd8v0raBg==,type:str]
  known_hosts: ENC[AES256_GCM,data:Sed/F8dDRhYRzEl+i5g4rcDwAezX+oVyZS5Foggx7X04HsSsP77TXRVgJsf32WjkNv8ev7sWGO5NCSpaOfOW/mZmjW3G/S0sNlzgmpC5xNDkZpKK6sTF1Bru7hWpdBOw0e3EcVwEghKwzUm276uEEXxPMfhaM7HkvvZ5FoCv4IwrEVfRE30nG4dp5ryux+SrLpM+ET0g6I6/6B5ily0HDpRym23jqm5pQgwSpqYAzO/0RMmotYKczG/E1BSz9bnf+WeSDRt9ClCpyRLewcRdDEEfm/T9aFYxZCfuy8MxhHvdkoxL3qD3JuWwy9ViNfN53gtwuPYNmcGONY7PidpU9wrAwDK0LXVSotNjBx5n0V+nio8hhsKn6gqWVeDmfNDEw2I61TWX1eFnOwpe7f93Ee1PtHK99Um6I1EzPrgKukuvQ2b2/rwAPnaP+JdZz2DO6ePKbqwKUjpMCn3gtK/ROF9N8twP/0uZ7QSAiAlfqaBmO1V/lIDTImizk47wQUj2bRZWgn2KAcp9PIJwoQUwUOgGYArqitEXWg4HGj5DJxDoBXOyyH84eTluPhH3mo8pHpGBRTgcuAONwi3lQNfgzaVqQHIHbcpvucRuqvCvm4zuhN4Lq5N1YafIDKYCkEJwODY4lfBTSYn/uzNpZvM5D1xR7oH+YxvXBls4fJlZnXzOYCKu4KVCets6wvGrvhvQWN24/LKIYv4xVBozeDT7kMzjB3CRGHpuqUvUpUiF2M396LX1WP47aDu/FkGFc0YZwApTjSSiOQEvsIavCk8lVRAUcGfpodwhZkM7dEcu0NdFWIS2htQtKBi0QQzp0iz3dP8uo1G2tQ54Yl/NRim2F16cOxkZlaogCWH7lHFamaRUpq9GgD7XyjMLgdTdtvpAD6OSNft9/QnpbmQ2X8koonxcKj3JTwnP0kOsLxon4tyWa8dhiLdZqlDqkolvzxHUNsEUsvD28AVjvzn7vjvjDmZoZq4v9KE=,iv:eS18EtWL4G4ONq/HiDzNdTnLocZaoNlbkLRJa0CxqoE=,tag:y39HH4nN38DV+iQJd74NXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M3hyOGNEVVdRUks0aFpB
        dWxDUnZaazgwcEduM3A5djdNdzJGSWZrNmpFClVyaDRjUTd5WG1qNkVXTTdUVXla
        ZUlRK3R2RzV4MTVPNDRVeDdjcmxuakkKLS0tIG84L3FpSmRJY2VqYTVwM3Rqc043
        VE8vUjNBVktLRGpPZzEzUUI2NEhpbVUKp+n8S6+jc324hzm9H6pNd5wsRw1+FAT8
        REVdkZ/T8h063VA9Dov7Yi6+BDntZWa6rwPLkwkwVKIegkEJfJXhAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T20:39:50Z"
  mac: ENC[AES256_GCM,data:atfq00Jx0RRxrY/j1E1Dvf3E3NCr49lpfI3fWB6qKbJYSNsq/y9ZmOd8EPY9suQXmot9QmNjTNtD7/5jsiWtnjnm1Ll084z2Elq9ToxrMC+/omwa+AxJmTUd/D03mhW5ovuBIp0p4lJwGWug+MX20Y38GUOk+o7tLTxqHU2NA8s=,iv:aYDLZ+ITqnSTtuHlMurgUNOgiZkcPv6xnxgHXRghGuU=,tag:nXsIESF/I1uDJ2epaN1bNw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
