apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
stringData:
  token: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M2UrUXJNVHB4SFBnUitC
        aUJKamVEZHlMNGJTWXFBckk4WFczWnl5VUM0ClFoT3E5OTU5MWY2YlhJekdtZkZt
        ejUwS0wzOFhVTGF4Zkx1MUVUc0hZc3MKLS0tIFc1S3FPbjlMOUZDYy9aWlZDeGpy
        WFp5MVJNdDA1L2RJMFRVbndHM29ZcHMKGcHaOWy75xppSteS3uFLJCT5qFA+1JaU
        RuyvWVWXn98ROchBuqw+NuLpcQMw5YFC8XnK429vyJ0vq66tRaf42g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByem9KUnJBUUFJb0RCN3RQ
        N21ta2E3UlVhVkp1OUZvZTBPdm9PQ0pQamtRCmp0Y1pJMXFYVEZCMEdyb0g2TDA4
        NjBTUHN2b3JYUVIzU2lOVjBTNXloMWMKLS0tIEt6ZitlYWFlMlBBNm14NjdrZ2pO
        UEIwNllDTW9ScVpEUXlpWjRzSW5GVFEKTlN0nj6n3k6p8agbT9bzH8Sz4w0xgPZ2
        eKxaO/jjKs4ZN2kx0pYg1jVbjEPm6bKcKrvJp1p84Fbad0H0zXzNOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-01T10:24:01Z"
  mac: ENC[AES256_GCM,data:WUjiyx1v6mh1PetZd6W2OwbLvJ4c9SBLX+BDeEV06pb9sCgveBPfFCm4xjTIYh2Q0U45/R+esq/YaByFm6IanGgzJgEoSSMEQyIOVmJwiHet0tpIRkaqg2o4YqYwSi/JKAzksbuqvfxiwydCBRZW1GKYM5OWRsc9Hvp9yBO5lHc=,iv:e4BUf2NwdS3NIl4Wh2jQpeqkukFmOg6NmYMxP/h+Nyw=,tag:XEJQ/+ICz4i2ac4vEpirdw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
