apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-secret
  namespace: default
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:sjCfvEzbhFwxcYVizg9bcDMAvz2S85ijIwWgfZOQSJfgH7gQFZQYzEkqEI8=,iv:sPVlSa6xOdfWdbjMR+2qxNByp5bVk+mzsov/O9eHAnU=,tag:gAQlg+9LHQmoCVQQg6Obpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaWRyeVcyaGV5aUlxY2NX
        QThhckkzRjIrMkNEb0hDVWN0NkVXajdBc3dBClVuTFB5VEp3TWdReU5FalZOQUd0
        RFZXeVhtSWtCc0FLUGs5eEtYa0FSdXcKLS0tIEMxT2RMdGc2UWQwUXZoRlVCTytq
        MWhGcVFFSTJXSldDRDYrNWJOZ2d3VW8KqCmyKF+0rqJytRVJ80s82yU9Vr33hWQL
        hOktdCeAS6QQ9XWUQBED8XJbDTJPZMm9fbm2vidT8P88xBb3ePzZ5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1c77wyzgh3jwz3w8mkxeqr9gzp68nzdaynkan2020d74tgps5lv0qxcq9l8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T15:49:50Z"
  mac: ENC[AES256_GCM,data:a+EONwyKr6aS3DEobMdttgT5s9dNzvz7nZu4t2cI52ezIaXrvQrQtBixRuKbuTSb8W8FZ7bgTt1BeuC8XIPKXJi8RCjaY71Q0EuQgh9w4/3p7P9pP6k4cMUaQR8Ru1Rn7vykxP8NWOxNnV8Shs/7sSAo29Tk37k3pfyFwv9j9i0=,iv:IX7UrBesgZ16DITTIdWnv99Slhy449SPpRixclcAsNs=,tag:H1wTgPPZdtzOaRjr0s5Nxw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
