---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clickhouse-cluster/ks.yaml
  - ./clickhouse-lab/ks.yaml
  - ./clickhouse-operator/ks.yaml
  - ./crunchy-postgres-bootstrap/ks.yaml
  - ./crunchy-postgres-cluster/ks.yaml
  - ./crunchy-postgres-operator/ks.yaml
  - ./valkey/ks.yaml
