apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - apiserver.yaml
  - kube-prometheus.yaml
  - kubernetes-monitoring.yaml
  - node-exporter.yaml
  - turing-pi-thermal.yaml
  #- thanos-query.yaml
  #- thanos-store.yaml
