---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-exporter-rules
spec:
  groups:
    - name: node-exporter
      rules:
        - alert: NodeMachineIDCollision
          annotations:
            description: Machine ID {{ $labels.id }} is duplicated among {{ $value }} nodes.
            summary: Machine ID collision.
          expr: |
            count by (id) (systemd_machine_id) > 1
          for: 5m
          labels:
            severity: critical
