---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: pipelines-aggregator
    files:
      - kubernetes-events.yaml=./kubernetes-events.yaml
      #- syslog.yaml=./syslog.yaml
      #- kafka.yaml=./kafka.yaml
generatorOptions:
  disableNameSuffixHash: true
