---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-unseal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openbao-unseal
    template:
      engineVersion: v2
      data:
        BAO_UNSEAL_KEY: "{{ .BAO_UNSEAL_KEY }}"
  dataFrom:
    - extract:
        key: openbao
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-snapshot-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openbao-snapshot-s3
    template:
      engineVersion: v2
      data:
        RCLONE_CONFIG_GARAGE_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        RCLONE_CONFIG_GARAGE_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: openbao
