apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/ed9eklBYONPBC8R,iv:CILQRJ7hOLGFwIGvYiqhIyYwpe+QJ7vqZlKdVjrEL8c=,tag:5yznqAP3WDwKiJe7Ew5QbQ==,type:str]
  TZ: ENC[AES256_GCM,data:PrJ/1PTbn7mUSbHruw==,iv:LPaWQaAi8r/R2c5CqcCSimxBb/wFgkv7+wLFw9j+HdE=,tag:bM/ss6h/KMFEX5ZpN7Uwkg==,type:str]
  #ENC[AES256_GCM,data:uH1QEg==,iv:K2VKpVPf8ee5EEv7BnFVaFoPsiHS8NCdiT+Y6Kv4Sbc=,tag:0X8KmWzk0YbIwl9kUqLyYQ==,type:comment]
  #ENC[AES256_GCM,data:XH3c,iv:QByFQ88U5rTmJKELm6rmiJyx4f0UCwCR9V4zMEJgW+U=,tag:BfFzrkndG9G+YgDYz+PQ3Q==,type:comment]
  S3_SERVER_IP: ENC[AES256_GCM,data:koxMvJK64lMTXQ==,iv:uKZnHTlUBrsqrV+Y5zUdddIlnGAxGfCEiglPukE+BzM=,tag:0TC0k1uvMQzieignmLA2lg==,type:str]
  #ENC[AES256_GCM,data:P7Q+/qEhfg==,iv:JknGADonYRvoykdpxeT7Fw8mY/bD2XMToktBK9DCnGQ=,tag:eOlRkqys8h/wJY+yj+AmDw==,type:comment]
  SMTP_RELAY_LB: ENC[AES256_GCM,data:ye7gAn+NEMVUUDw=,iv:+U4TNcuSRf7XVTBjpJ8D20J/Q2hM/hR+zKER2/EP9Hs=,tag:tHk6M2/NDIuTQaEFD/DpKQ==,type:str]
  CRUNCHY_LB_POSTGRES: ENC[AES256_GCM,data:as5FFJArkZL3kYo=,iv:Tu0LYLrLoUxR9s8zTvXbdiuJ89mDTwy5pxXSvxIiYI0=,tag:ksokXOCSdw7Z+P2dRFIhUw==,type:str]
  SYNCTHING_LB: ENC[AES256_GCM,data:2BU3p9zeca4CO2Y=,iv:ool402axVL3usdI5Ow3+8jdYhpxZzsNUt3fyFLYW4yo=,tag:fg1GPH19dGNluykfuxNmVA==,type:str]
  JELLYFIN_LB: ENC[AES256_GCM,data:z549kgw1U5Qw4z4=,iv:7xLmmNDkh/Ty9yaL5AGMXfskXNxuQLxDmUlAkcMEOoU=,tag:x0EOgYL/FFaA+5+OUFIdbA==,type:str]
  #ENC[AES256_GCM,data:JIOV0kM=,iv:sY9CdUtHbtiEF0egzHNKE72bz0Ek1Z3dYWelC0UsjCk=,tag:URJo2VL71AFg4oYawUyByQ==,type:comment]
  SECRET_LDAP_USER: ENC[AES256_GCM,data:m/lenu6RIU+c6M3z,iv:sjBs0mUtAVnX5xnsrqSNVhIxQOqB7Ltxq0Ls8R/kXSQ=,tag:nnhOauNmgrRnH5IP1pfhCA==,type:str]
  SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:sZIsazAHwqVrYMUgepSi,iv:ypkvGlDiVxUqWPi9URG2ty8MIuFZ8iTkkxQ1NtiSRCg=,tag:Up1AfPs0J6Y4+lkIM+t2KA==,type:str]
  #ENC[AES256_GCM,data:UGO01F1vkJM=,iv:H7dHZ5th5JRIF5WH9kjg0mbE54hgbuSkpyXN9RZSSYo=,tag:npd1bUYRpgACBaQdMIpPBw==,type:comment]
  OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pw+2FLcZLw+P07dUT9OcrRG78IsQR+C04uNfxvTVcFuMwIhKZRGgwSy3kMw7T5NnooRiX7cwe/UNzm2uuplS0Q==,iv:JyHnm3cyYrq0nAioQ0SwYxAyjW7MYg/6MqlJd3oANhc=,tag:T8gePzCkVHMt7Ucr/Bw2LA==,type:str]
  #ENC[AES256_GCM,data:tn+J7OatteVn0SM24SGmKl2Tkvdey8ug,iv:Sfyg7wiiKQ1x5VCP/IZDsCw3+42GwqObwtEWiA/SSGA=,tag:GcwUD/y4s3ydhRMlMSYF5A==,type:comment]
  KANIDM_ADMIN_MAIL: ENC[AES256_GCM,data:LAA8IumntLj+VdIyM61J37WInA==,iv:+ruBthB7INr3boDgs414lXLH8gIVSvodqfNFmKG4Wh4=,tag:vtbh56/U5RPRd96P63nX5Q==,type:str]
  KANIDM_ADMIN_DISPLAYNAME: ENC[AES256_GCM,data:pVkftXg=,iv:zqyDE5zY+vxAfDkuC53YJmf5/dZyoircam0Z7s/LD7w=,tag:LN5444tyIOJkBZ9PwKNCvQ==,type:str]
  REBOST_IP: ENC[AES256_GCM,data:rTnpr4+W0fkWxQ==,iv:QdIGMrZTmUKawyQhPRWE+Kg9tyFsRGCkGz4S7DramIE=,tag:DRGK2Vhtd0p0AWPv/NUexQ==,type:str]
  REBOST_MEDIA_PATH: ENC[AES256_GCM,data:bPm7Di8=,iv:GcnEkmWobD8sQ+PAZVVcwwURDT6qrC3UOJKwJ0RuhMM=,tag:RODSK2gJuOB5XLsnw5KgiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGFGeGExRUNFbmtkNWpy
        MkJuTHdlRUJ1OWxremNYVmhPajlvOFhkRjFnCkdKR0RZOWY2OGtrSDFsR1ZxSmlJ
        NEVQSjlkU1VYeDRMa3VCeXpPVmxBNk0KLS0tIDNDOCtmZWxXUkp4S01QRFBjZlI0
        ZU5CNEVTaksvRlNNa0w0UzNrNU1pMU0K6ZRHeXoaXbvtBNfolQ3Korf33LwQxqq0
        JKr6WbcFUk9g9Noxai+j+xxX4XJ7/r23osfEp4uVXRe1bOSXdpP+bg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T20:48:52Z"
  mac: ENC[AES256_GCM,data:oQxQ6lij9oX+BCAk8xFNwAgrDf6GAZg0cWIsC4FAHT0FnkqoPZd0rbIpGeTmzVg+CbUpPnS9w1yZNweBsA4Vr6m9GGmmJmN2j/cOU/LY3SFzUathZwgW/AvyVReKX32RZNxW+9q66VjH3inqw2ASR6s3dM25AHU/1N/++ITRgcw=,iv:6DG8sEuyxwNxSrTHpKw6GKmNltCXtGzvyaHHFstNuXI=,tag:7/JBUUwVkSYMqhLM7H9MHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
