---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
        UTILS_SECRET: "{{ .UTILS_SECRET }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_S3_UPLOAD_BUCKET_NAME: "{{ .AWS_S3_UPLOAD_BUCKET_NAME }}"
        AWS_S3_UPLOAD_BUCKET_URL: "{{ .AWS_S3_UPLOAD_BUCKET_URL }}"

        #SMTP_HOST: smtp-relay.networking.svc.cluster.local
        #SMTP_PORT: "25"
        #SMTP_FROM_EMAIL: "docs@${SECRET_DOMAIN}"
        #SMTP_SECURE: "false"

  dataFrom:
    - extract:
        key: outline