---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app outline
spec:
  chartRef:
    kind: OCIRepository
    name: outline
  values:
    controllers:
      outline:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/outlinewiki/outline
              tag: 1.10.0@sha256:cc9f1f05fd7cd316745b5fc9cfe01e681b1b4cf97705d1d812a5c778d7986cfd
            envFrom:
              - secretRef:
                  name: outline-secret
            env:
              OIDC_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: outline-kanidm-oauth2-credentials
                    key: CLIENT_ID
              OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: outline-kanidm-oauth2-credentials
                    key: CLIENT_SECRET
    service:
      app:
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["docs.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 400Mi
      limits:
        memory: 2Gi
    persistence:
      data:
        enabled: false
        existingClaim: storage-data
        advancedMounts:
          outline:
            app:
              - path: /var/lib/outline
                subPath: data

