---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkding
spec:
  chartRef:
    kind: OCIRepository
    name: linkding
  values:
    controllers:
      linkding:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sissbruecker/linkding
              tag: 1.46.2@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
            envFrom: &envFrom
              - secretRef:
                  name: postgres-${postgres_cluster_version}-pguser-linkding
            env:
              LD_DB_ENGINE: "postgres"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 9090
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9090

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Linkding
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: linkding.png
        hostnames:
          - "link.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
