{
 "title": "Kubernetes Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "probe", "query": "probe failed" }
  ]
 },
 "panels": [
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kube-prometheus-stack-operator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of running pods per node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Running\"}) by (node,phase)) by (node)",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "Top 10 High Cardinality Series",
   "type": "bargauge",
   "description": "The query calculates the number of time series per job and metric name. Only the top 10 are shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,(count by (job, __name__) ({__name__!=\"\"})))",
     "legendFormat": "{{__name__}} - {{job}}"
    }
   ]
  },
  {
   "title": "Running Pods per Namespace",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_phase{phase='Running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU request % used", "type": "timeseries", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 } },
  { "title": "Memory request % used", "type": "timeseries", "gridPos": { "h": 8, "w": 7, "x": 7, "y": 13 } },
  { "title": "Container restarts/min.", "type": "timeseries", "gridPos": { "h": 8, "w": 7, "x": 14, "y": 13 } },
  {
   "title": "CPU Cores by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores) by (node)",
     "legendFormat": "{{node}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum Kubernetes CPU request per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Prometheus samples ingested", "type": "timeseries", "gridPos": { "h": 8, "w": 7, "x": 14, "y": 21 } },
  {
   "title": "Pod Warning Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=\"event-exporter\"} | json |  line_format \"{{ .message }}\" | json | line_format \"{{ .involvedObject_namespace }} {{ .type }}  {{ .reason }} {{ .involvedObject_kind }}/{{ .involvedObject_name }} {{ .message }}\" | type = \"Warning\" or type = \"Error\""
    }
   ]
  },
  {
   "title": "Kubernetes Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{app=\"event-exporter\"} | json |  line_format \"{{ .message }}\" |  line_format \"{{.log}}\" |  json | line_format \"{{ .involvedObject_namespace }} {{ .type }}  {{ .reason }} {{ .involvedObject_kind }}/{{ .involvedObject_name }} {{ .message }}\""
    }
   ]
  },
  {
   "title": "Container error logs/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({app=~\".+\"} |= \"error\" | json [1m]))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  }
 ]
}