---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr
spec:
  dependsOn:
    - name: envoy-gateway
      namespace: network
  targetNamespace: default
  path: ./kubernetes/apps/default/bazarr/app
