---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./clickhouse/ks.yaml
  - ./crunchy-pg/ks.yaml
  - ./valkey/ks.yaml
