apiVersion: v1
kind: Secret
metadata:
  name: instaloader-secret
stringData:
  profiles: ENC[AES256_GCM,data:U98Yhg5dAn56VZIBjF1Nkh5M,iv:shnPl7mOqLayVAUDNlqoUTmIxQVZEOv47easztMGH48=,tag:0662TrE/KgeJ/E6pT+cMcw==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWE1aeDFoSzYxODd2RjdV
        dU9FZDlOUnNFZlZHRVRXbXdZbjRnby9vUDBrCkpUTjRIYU13YzdFV3hDUm9ndi9q
        RFp3Y3ptSGNxcTFYTkE5UHdYR3RzQWcKLS0tIEJTSWpLWDJRSGNaY3RGNUYzSVVC
        di9uZldQQzF5alo1TXBFUnpuRUFYcUUKaFJdONJDBtyHWH99dh8rfpCBe6pjkEMv
        fXDjOT0LgEe9UEEBGUNUZeEoq3B93WALG2iRTNVj2KaDrAc6HeadyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T20:29:52Z"
  mac: ENC[AES256_GCM,data:dc5yn/i4IzldxR5IGdLNJE7aJU1aKTsa20VjVYNEY68+Bo0FZtedqSsUddNvTkO0VMwArhfH0dGgzXpeiAuy5JnP289i2Ph88Fhhk1L1PIWyTotrsiucuGDXpHQvhBpAcU4YSNtvzq7+VRlW5OpDHHCZIlaPA8ELS12uLaoetaA=,iv:oNXUyiFrM9a2PA8daqUVdgJlu4R4ojZduqRKbuRuOH0=,tag:mdn37F2vZoPzONkQ/mvDJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
