---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  chartRef:
    kind: OCIRepository
    name: filebrowser
  values:
    controllers:
      filebrowser:
        containers:
          app:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.63.2@sha256:4dce87308b9f9cfbcf8d0a284fc9565d2b515530a6bae2d920b388161e093f26
            env:
              FB_DATABASE: /config/filebrowser.db
              FB_LOG: stdout
              FB_NOAUTH: true
              FB_ROOT: /data
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 411M
              limits:
                memory: 411M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 65537
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            port: &port 80
    route:
      app:
        hostnames: ["fb.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: filebrowser
      data:
        type: nfs
        server: ${NAS_SERVER_IP}
        path: ${NAS_SERVER_MEDIA_PATH}/Library
        globalMounts:
          - path: /data