apiVersion: v1
kind: Secret
metadata:
  name: forgejo-workspace-auth
  namespace: develop
stringData:
  identity: ENC[AES256_GCM,data:8+wH3CjkFR5+ZDOBqXKmC248qnHa5wP+N100x+kd2doxMIQ6nyItOPCfgtNLQ+jEOAYB3v6a3xNS932RqP2HCgaMKnCQrI4eI0Noom/0wuH3Wt2aqWGrmGGLyU4jmUv/yJNRc5Yg2Y7CnV01GNuvQQpIhgJus6fKFuBaTpF+qX/EW4bAxpLngf8O35ZRJkSrF45Zn5T3gLUWJngfFGD6MFdK5LxJBlb4kPxN7EAMo7mSxuMX1KT78Rnsq4fbHOcNhMruRAn24XTun0SMeVt3YGjHfNiHmfQB5kF9ngRE7PAq89ncvbRkbN/n7F2+w2syCCeeuL1agxunpfz+6quftOEr7q59Yh/opboAWqinaxjiXzGp7VUEzC20BR637qUdi9TZ0z9XsB7AZnGIRj6fknk0Zk8uOUzqkmV/CGnYfjyg5mqIV1Mhk2yAh4Jo4lu+j3lc/YJ7j0RvM80l9JzdoaA09oK9CNePrGnyzGB3Nz4UZgB70rIhfSN56H3HATabbB6/w13s+J5ljy7N8i5TmXFImctD0JLYQmiq,iv:Fo037pfyFThr8phukRdQj9lXKcJOES71/RDjL18F1Hw=,tag:q1/FrGxOChZDQ+3yGTzZJg==,type:str]
  identity.pub: ENC[AES256_GCM,data:KslWm0qqD6RUySNBEgDVI1CZbtRSWLVL0R7M+SCTTaz/CoOJG3I6aXT76duJu9y1NLHOoaas47Mke8H4OEyASmQN9r9RY7VArACI0qYFKrTV9T4KGuW72hGJZk59A0nlmdPepII=,iv:7AdOhDA+H3DOXt0H9dPskKQv6zAEL7HHKnbrS88kyJ0=,tag:GP/NpzB9dJeuBuTjc50McQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:O6WaOJyvwOSSRaNaT56z7l0tDCGreBdXGdUJxvvRIWg45gL+Onrl00M48lBdibiRVfM5TSE1tCS9sSeMC5GDzEcBz1lRPvXSY4F26JpTtwXDWbob/9kphJTeXZLSULCT1ctoBY3t755OrnV3RrDaeNYnq0imG937yi4yQWVMBKGP9oLDdFf/1HcmkhOph2+qRj9efzog0CWDQ/J0bt1EChZQlcjhvzioYKTMKPJk2tzBPb8mznNh5fVrdqkNLc5Pk/vvgKgSLnn2s+TuiVfOFMq7IA+4FyyjgTznmvBmoYsZ3Nm7kqq8yN/fLcdZfbe/v2NEnagCV74lXx7VtWo+CMYYfWKwkl3AUMF2nHbdJ+isZa1XmF9F9JgcAVQpmywQnxM2KeFWZ0gc+a4eGCGRJekF/AxW5rIddoHOBaRFC9BVunY1mp9HakkrseM4+QoupiWt5qLfSU7R6ZgsvDmfAa98pHNVi8HVQhRNZciN6w+Q2mj23HzBnCAF02QB0p3oCOKddb9pbF1xooSxLl9MZ1+Bov5X+uCGYsG6BArtwedqfa3FuYzFgwvGBl84Ct/UwOnPp1udA+V3QcaYWDTJMxqExOEmKNCj/TPIafTiY7HLhlOjUkU1tuFCMGItNe5KQNNjp1o/Boti3KPYHAM/JPoXu8r0MF8JKCQC9EyicvljaGFdAgULmhLMN2zqE50ExqTB12O27SBnaGInRc+997xdpK9LHsF8NGjQEpFGhDer0WdJP0xoikgDNKMNpIlaW0LMUZdd3fKeKFxNXPaqitBZ1fiU7GXEeq5KqVweYf54JKF09rNMn3eQ2kz1TJSLC/sIQJsbPtSHqVfB8eUGggAY1IzVcnhBmvcR13AgAGHq9l9kkX730Fp2Zht19ibwTHDCAzNH2gYfm7xVbgH+Ma7GX/drDY1PKAgETciJDuebclb9G3t4x9EC+D/hwzfpHxS43TIDcmr3wfUVoSTvIXFGOlsH,iv:b5PzgG0bijGZ1nJEGK56MScZFQJ6OuzeGHNDvDDveqI=,tag:zSrJDVRZ4lV2UVuJeWAeRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFckNWdCt1MTZESDl1UlBF
        SG50L0V1V3Nzemk5NXB3Q1l0S1BPUzl0M0hrCkhFZWZCZ1Z0blpKelY2NzZEVVRM
        UWJGZm9Hc3d5SGhZK2xzNnBMYmI2ZTQKLS0tIGRsanY3cUFUamRwbzU0bGlCc3ow
        cnJwWlkvc0NlVUNhS2tkK3hnVU1DZ28KmjVrMkMepQ0CyIP8rch2sI20DiM70Uvf
        ZtU/mqUeHaKSQM4qoILmvfHehxTVNnSoB38eVCmA8ZS0sySCHu/WyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T07:58:18Z"
  mac: ENC[AES256_GCM,data:itnnUXiqa2bW1Fiaa5ePLTj+I9bIfrieq0GyLysnajyl4YCOkzrGrL0JUUeopPLIjKG3EfWzRWSJqHhLeMW52zztzX2E179pCFKOwd9uE+jWV59Al4ugzqCRvcKvYRPB6DWBPl2faKFSfQz2pTrZQaNze+OFv4PUAq+vgvuDndI=,iv:b6coIERS1Hh4v29KkppAst+jyg2qdfDXZQxi32afndA=,tag:ZQKohQqjP06RhHSDhWIhkA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
