---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valkey
spec:
  chartRef:
    kind: OCIRepository
    name: valkey
  values:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources: {}
    initResources: {}

    deploymentStrategy: RollingUpdate
    valkeyLogLevel: "notice"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
      prometheusRule:
        enabled: false
