---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: valkey
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.4@sha256:927298fcaa2287353c823ca3412b86d630269d34388bc85271303c5b758c2015
  url: oci://ghcr.io/valkey-io/valkey-helm/valkey
