---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent-bit
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.55.0
    digest: sha256:6e3b10c28c20b724dd2646c500c7647de60918d37b5f335fed274d9a93b59ab1
  url: oci://ghcr.io/home-operations/charts-mirror/fluent-bit
