apiVersion: v1
kind: Secret
metadata:
  name: discogs-watchlist-secret
stringData:
  DISCOGS_TOKEN: ENC[AES256_GCM,data:jVQZdjGL+QD9Pzuej0ixjRe3FtGul9isOqg652xNCSEBrQGNCLFacQ==,iv:UIbOcZnPOHxz66p9NKI+6rE5ZxJEfeyKlLUB/xgqPgE=,tag:4IA7yGwAgIlH5IvG3DznsA==,type:str]
  RELEASES_CONFIG: ENC[AES256_GCM,data:UNp1ZwILT++swCehY6kuvk2j1m0SU8wIC2fgl1xqgMsJQvqt6lwvZP19GRghGYvda/ZDiy6sw3p8TUBea82kSaQG6QLEjmogxq/dNg8AIODCuZIdiNVZF3XOmp3x72dcWOUtgUOL9qSBOCPgqR3iviVN/MZzVQTal/dbR5s8NYklgS2RtmKIyBylxJxWCCiK/0f8gwAyGelquaEJgyQWUCbh0tpn,iv:ihWWTca8sw9C8EXwNMFruS+/4t0zRrfnAIE/DSnbrnc=,tag:NEIMj0+tocWhhv8oMlcI1g==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcm1pdzR4am54RHJJZ29t
        aHdpNFZZcWdqV2xlODJlMHRxRUVNTUdHTnlZCnlSVkhsbjhxeDNZOFJ2ZHBsWG1v
        Sm9YWjgzWFQzeEVsSGVPcXZnaXF0anMKLS0tIFBabWJnZ2VGR3RvOUFiQ09VVkZB
        Y1U1NStFaWxUM0dtNFhSakZTZEJYU2MKzrTvJdmNd8tjLr9viTKWBrAU2Tm75e3w
        M7m6teuLS9AOgyRgFFsSDPBOoYi99/HoeVxu0X9qoQv6FM3AtFB+Gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T18:11:18Z"
  mac: ENC[AES256_GCM,data:+OpCD/yNRnlLJfMHbHWdqPMJFwgu9nB1nJL2DsWYaGyedRev8BLAP/I6x8CrN6qR+2pRL66yDEFFKT0riXvLndaunMx6t4NWCKbGodWk59mLR3BsInqU7jeqXWw8jNlCx8p571mtYiIh5dtReJBsRn+bFpjYd0a1qJPHyGM28DM=,iv:J+LimSiimeSNmRXtGprK7cZMIYGK6WJ2XTUXJEyXtEM=,tag:pN5hPWZDE4NhHDrLc2E9nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
