apiVersion: v1
kind: Secret
metadata:
    name: discogs-watchlist-secret
stringData:
    DISCOGS_TOKEN: ENC[AES256_GCM,data:jVQZdjGL+QD9Pzuej0ixjRe3FtGul9isOqg652xNCSEBrQGNCLFacQ==,iv:UIbOcZnPOHxz66p9NKI+6rE5ZxJEfeyKlLUB/xgqPgE=,tag:4IA7yGwAgIlH5IvG3DznsA==,type:str]
    RELEASES_CONFIG: ENC[AES256_GCM,data:nk1ijXp7ZGCe8m2ZiArbiPcFDhiWZDjGAFRbEtk4wHZnmz+ZZSbjJFMND6AqvqQZJJknqDLhofdwBdyA3TCg4FYunFJS5ROG5PM8EK7S7/FqUEJ9dXKwzY3By3sHhBliOhbCBnUj+9QyssIhfVmTtvVBlLjYjPlkOH1RVuhBcm37qFgkAeODV6evhaUSyDMsSL3oligqz4atIQf3Xwvxm5yHNjkwzOD1313D6ypmi4JjId8EP8oNh66xdUoVIZlUoD5Uh3RBBP3V00Tro2FYUPJY4XJAuHbTSpQE6CQbNOPs2A5Ns1YQnwbmBsU8nEiAK8iO+IadmCOXrhPgauuGrzyv2Mb+DVLN1+zZP9wRrCVviuHZaZSsriF4ySlE5R07M3NmMD+1eeUpJsFdFWrrcK6Vu84BVI+VxBGoyCkYDb2BAdJCa9Mh93WXuxCy4KWAh6+v+j5Sv4e/E/OCF9Bcl0bRsnFrc7IhuB2AdjTlaoP9ZCfQSjdJ87YYHEDFAhX6BjypiLZqSPTNrL3IO2DHjF9FlR5k3TE9gzKnjBIPhoHLl5YQ+XHJecgo1X7geqtllX5Klk3bW33QOxVuMhHrulBlLD0nCz+IH0RWkkswTwG/wkhgYACn6ylDVHL69GSUAsS/+iIhpby5jgg9nXJPhsXn0hkP8fKq1Dfpj8J5PL63owaVLP4gJdtCv5lFYuaoEeEwM+5ojFJL2xBrF2OfnQoervUl8oSHROIOLJE0+ch44DuLNckAqQfu0ovdRDGYH+CZ6Sd7iwAXZIcPUl+Jr943cjjRxpq3WTch8NutElLQlJxKbW5DAoZIPgwKljrdL1CLKap+DYa2lE0S7YpxzPSDtj6+s3B5Ld6Yclis+/LuvaiW+RIEM8axKV4JHZ4=,iv:hhiNYXSqdfeoS0IH9DhE7OxlNM7VFZFgx9G3B0ueZjk=,tag:OPxzcUQ5/eAPZUXX9StxVQ==,type:str]
sops:
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcm1pdzR4am54RHJJZ29t
            aHdpNFZZcWdqV2xlODJlMHRxRUVNTUdHTnlZCnlSVkhsbjhxeDNZOFJ2ZHBsWG1v
            Sm9YWjgzWFQzeEVsSGVPcXZnaXF0anMKLS0tIFBabWJnZ2VGR3RvOUFiQ09VVkZB
            Y1U1NStFaWxUM0dtNFhSakZTZEJYU2MKzrTvJdmNd8tjLr9viTKWBrAU2Tm75e3w
            M7m6teuLS9AOgyRgFFsSDPBOoYi99/HoeVxu0X9qoQv6FM3AtFB+Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T19:56:04Z"
    mac: ENC[AES256_GCM,data:lpf+ZTbbPxhACVbQPZdMADRzxGAyN5S+Let2OL9qLNyaJ9Vl7eFYOXtvGcV+WMfB3gg+ZRAz/KlxcP5uPY00YeXuQDECFFLp5H7IHlTZgtiJ8KmNfXDTGmMWkNeKPRFOgYsNb4XLeOIdvBmJ9S4X2sFKpkYDWAFGiYo63SrTJBU=,iv:efjKM+06BqEOZYh7UlYJYIo6OR7LJJOtJea+I0EYzac=,tag:cW6LjPgXuK1eYNGri1HMDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
