apiVersion: v1
kind: Secret
metadata:
    name: discogs-watchlist-secret
stringData:
    DISCOGS_TOKEN: ENC[AES256_GCM,data:jVQZdjGL+QD9Pzuej0ixjRe3FtGul9isOqg652xNCSEBrQGNCLFacQ==,iv:UIbOcZnPOHxz66p9NKI+6rE5ZxJEfeyKlLUB/xgqPgE=,tag:4IA7yGwAgIlH5IvG3DznsA==,type:str]
    RELEASES_CONFIG: ENC[AES256_GCM,data:DFbEE67FDHksGgVC1OPcqjc59ZzjXgzQ0MoJ6NNIhfLVvdNlvRPlvFUUt4cwKZzdC8X7v7JBXDnLsahuZcXMFvADpP0e0yj4pC6/yuBoaM8FDua/aW+dicA/CurVtFik+aAFv6WvK43/mls5lbKJGDLuctbYdUBxEmBx4gLnGVgKNfjQVtYjbS2v959uvf7wlDaP2lu/4DqBNsYsMWpIU72zsRDkCM5Y3jFttazXnHe16f85UuT9Rnk3TOwKFp8AqQlU1tQ38EbKVrcjS1ln5su/T2lcl155Q3CCapmujH/vCCyI/ERCrpF6VdiPwaca5kssn3EOfKktdqnIzqXbI+eBPTmAVopVKNHeKtEZ71kw2lvkQgsRSZ7qZ8eA9fV/DqNvG21nLMGmVmcgWdDdNisHtWO8u7IkDAK2jGcKX/Irn3wVzTKr9FbFK3mLRCBXuoTUCdFxGTgEPV8sdUd9ewH70lG1yl8PKf4kO9udaz31Kz6pJlmyinpotwajt/4T6bZS4CT73l9kBn1SD5+nC9Am/MkN+i2KYvmzAa3ElW/hJILq/F3oMGDtyn4cfQmkZFqpqjkxIv9seg9woEyY6xwdGZJTr49RbL2wIjzgtAXGT5SfmRvFrknYOog5DhJFt1HjMCkKA2WIag99UmnlL40kVcsWaXV3Jzi4L/jTLjBsJOYVLQlGGO4Rh69e4nxwu8mbrtYTEY5283SPxKxc13edP5J4LYs/kWbDcTsyzgSbSk+vgDnKeqXg1lFmh+TMix+isSmHE8cT+5ijX/PYEOTPwkO66vnvWT/10DkvuQ+QLG/Efsf6DRyDkU8xLRf0/acctZo1+TJDeDLtgUMcYn61bt3MBMvMfgNOwXx2PihDo3MoJGae8q9lNbe69itQJwiQm2V3NwSZ7pMP888fkLrVyN2Ty1SlOi6nmxDMrTMSRiEY+bRwKH7Jml3sPKOldMKKT+ZjrfsUd0okJGbLLLgk1qF6q8rWM0X9uxWeAUrxygRKHwANCJ1bBcZ7izN33tAuR4+F6X6xRV/q0vCqmUN0tdGUrGaagmlTSKnoyxf5ASPAs234RisNJq2LH/jjC/i9/3ZqENYo7SLP,iv:3C5LLDuoMUjtSoLvm9W8K+wf3EIsZ5j4u/fZ1ZChxac=,tag:2i5wPkJanDuLZjtG6SsINg==,type:str]
sops:
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcm1pdzR4am54RHJJZ29t
            aHdpNFZZcWdqV2xlODJlMHRxRUVNTUdHTnlZCnlSVkhsbjhxeDNZOFJ2ZHBsWG1v
            Sm9YWjgzWFQzeEVsSGVPcXZnaXF0anMKLS0tIFBabWJnZ2VGR3RvOUFiQ09VVkZB
            Y1U1NStFaWxUM0dtNFhSakZTZEJYU2MKzrTvJdmNd8tjLr9viTKWBrAU2Tm75e3w
            M7m6teuLS9AOgyRgFFsSDPBOoYi99/HoeVxu0X9qoQv6FM3AtFB+Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T07:10:57Z"
    mac: ENC[AES256_GCM,data:/yOwdLSLpOGWNJw4B7Hakb2XUdXaVsHHiBGdWg7UZqzwniRGYM1O7493p9n048/HBrAvUmsiNWislwRncsa7TVHk1H4QD4uFu5D6lYZk/oU3s8wwR6/PDqpJQlXci+WJVJjY7OYJ5lQ+e6desQGTLQ9AFuj+AAwZW1mzWPhTwpk=,iv:fSTjlBlpWF0t5rCCVDIwBmvJhwpFT0oE4gC/kNyMfGo=,tag:HvniMwfCLWJdVJQuMaZpow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
