apiVersion: batch/v1
kind: CronJob
metadata:
  name: discogs-watchlist-cron
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: k6-observability
          containers:
            - name: kubectl
              image: bitnami/kubectl@sha256:6e9c5284a0dac06e84de9f4d97852d2e6513442ee7ec3a66d35009eec86e1e62
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: k6-yaml
                  mountPath: /tmp/
              command:
                - /bin/bash
              args:
                - -c
                - 'kubectl delete -f /tmp/discogs-watchlist.yaml --ignore-not-found; kubectl apply -f /tmp/discogs-watchlist.yaml'
          restartPolicy: OnFailure
          volumes:
            - name: k6-yaml
              configMap:
                name: discogs-watchlist-config
