---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-${postgres_cluster_version}-forgejo
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: forgejo-db-secret
      template:
        data:
          host: "{{ .host }}:{{ .port }}"
          dbname: "{{ .dbname }}"
          user: "{{ .user }}"
          password: "{{ .password }}"
    dataFrom:
      - extract:
          key: postgres-${postgres_cluster_version}-pguser-forgejo
