---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-${postgres_cluster_version}-pguser-kguardian
spec:
  externalSecretName: postgres-${postgres_cluster_version}-pguser-kguardian-template
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: kguardian
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: kguardian-postgres-credentials
      creationPolicy: Owner
    data:
      - secretKey: password
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-kguardian
          property: password
