---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-${postgres_cluster_version}-pguser-peertube
spec:
  externalSecretName: postgres-${postgres_cluster_version}-pguser-peertube-template
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: postgres-${postgres_cluster_version}-pguser-peertube
      creationPolicy: Owner
    data:
        # Database
      - secretKey: PEERTUBE_DB_HOSTNAME
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: host
      - secretKey: PEERTUBE_DB_USERNAME
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: user
      - secretKey: PEERTUBE_DB_PASSWORD
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: password
        # Database Init
      - secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: dbname
      - secretKey: INIT_POSTGRES_HOST
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: host
      - secretKey: INIT_POSTGRES_PASS
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: password
      - secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-postgres
          property: password
      - secretKey: INIT_POSTGRES_USER
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: user
        # Extra
      - secretKey: PEERTUBE_DB_SSL
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PEERTUBE_DB_SSL
      - secretKey: PEERTUBE_REDIS_HOST
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PEERTUBE_REDIS_HOST
      - secretKey: PEERTUBE_REDIS_PORT
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PEERTUBE_REDIS_PORT
      - secretKey: PT_INITIAL_ROOT_PASSWORD
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PT_INITIAL_ROOT_PASSWORD
      - secretKey: PEERTUBE_ADMIN_EMAIL
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PEERTUBE_ADMIN_EMAIL
      - secretKey: PEERTUBE_SECRET
        remoteRef:
          key: postgres-${postgres_cluster_version}-pguser-peertube
          property: PEERTUBE_SECRET