---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-peertube
data:
  init-peertube.sql: |
    \c peertube;
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS unaccent;