---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./arr-config/ks.yaml
  - ./atuin/ks.yaml
  - ./bazarr/ks.yaml
  - ./copyparty/ks.yaml
  - ./echo/ks.yaml
  - ./excalidraw/ks.yaml
  - ./feishin/ks.yaml
  - ./filebrowser/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./forgejo/ks.yaml
  - ./homepage/ks.yaml
  - ./icecast/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./kavita/ks.yaml
  - ./linkding/ks.yaml
  - ./metube/ks.yaml
  - ./navidrome/ks.yaml
  - ./outline/ks.yaml
  - ./pinchflat/ks.yaml
  - ./podinfo/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./srs/ks.yaml
  - ./syncthing/ks.yaml
  - ./twitch-radios/ks.yaml
  - ./unifi/ks.yaml
  - ./vikunja/ks.yaml
  - ./zot/ks.yaml
