---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: forgejo-secret-key
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: forgejo-internal-token
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
