---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-develop
  namespace: flux-system
spec:
  inputs:
  - namespace: develop
    apps:
    - app: forgejo-workspace-config
      path: ./kubernetes/apps/develop/workspace/config
