---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-external-secrets
  namespace: flux-system
spec:
  inputs:
  - namespace: external-secrets
    apps:
    - app: external-secrets

    - app: onepassword
      dependsOn:
      - name: external-secrets
      healthChecks:
      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        name: onepassword
        namespace: external-secrets
      healthCheckExprs:
      - apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
        current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
