---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-kube-system
  namespace: flux-system
spec:
  inputs:
  - namespace: kube-system
    apps:
    - app: cilium
    - app: coredns
    - app: metrics-server
    - app: reloader
    - app: spegel
