---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  - ./databases.yaml
  - ./default.yaml
  - ./develop.yaml
  - ./external-secrets.yaml
  - ./flux-system.yaml
  - ./kguardian.yaml
  - ./kube-system.yaml
  - ./network.yaml
  - ./observability.yaml
  - ./openebs-system.yaml
  - ./security.yaml
  - ./storage.yaml
