---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-network
  namespace: flux-system
spec:
  inputs:
  - namespace: network
    apps:
    - app: cloudflare-dns
      wait: true

    - app: cloudflare-tunnel
    - app: envoy-gateway
    - app: k8s-gateway
