---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-security
  namespace: flux-system
spec:
  inputs:
  - namespace: security
    apps:
    - app: kanidm-instance
      path: ./kubernetes/apps/security/kanidm-operator/instance
      dependsOn:
      - name: kanidm-operator
      healthChecks:
      - apiVersion: kaniop.rs/v1beta1
        kind: Kanidm
        name: kanidm
        namespace: security
      healthCheckExprs:
      - apiVersion: kaniop.rs/v1beta1
        kind: Kanidm
        failed: status.conditions.exists(c, c.type == 'Available' && c.status == 'False')
        current: status.conditions.exists(c, c.type == 'Available' && c.status == 'True')

    - app: kanidm-operator
      healthChecks:
      - apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        name: kaniop
        namespace: security
