---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps-storage
  namespace: flux-system
spec:
  inputs:
  - namespace: storage
    apps:
    - app: garage
      dependsOn:
      - name: onepassword
    - app: garage-webui
      path: ./kubernetes/apps/storage/garage/webui
