---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kavita
spec:
  chartRef:
    kind: OCIRepository
    name: kavita
  values:
    controllers:
      kavita:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 65537
        containers:
          app:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.9.1@sha256:31181a32f0dda73cae68721867028a7253d57881b58bea5754cd9e578e75421a
            env:
              TZ: ${TZ}
            resources:
              requests:
                cpu: 15m
                memory: 300Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 5000
    route:
      app:
        hostnames: ["read.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-config"
        globalMounts:
          - path: /kavita/config
      media:
        type: nfs
        server: ${REBOST_IP}
        path: ${REBOST_MEDIA_PATH}/Library/Media/Books
        globalMounts:
          - path: /books
            readOnly: true