---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: allquiet-sync
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: allquiet-sync
              image: ghcr.io/oscaromeu/allquiet-sync:rolling
              args:
                - --team-ids=536aa038-50e6-463b-aee6-389023206a9d
                - --env=homelab
                - --clickhouse-addr=clickhouse-clickhouse-headless.databases.svc.cluster.local:9000
              envFrom:
                - secretRef:
                    name: allquiet-sync-secret
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  memory: 64Mi
