apiVersion: v1
kind: Secret
metadata:
  name: allquiet-sync-secret
stringData:
  ALLQUIET_API_KEY: ENC[AES256_GCM,data:53CnY2E6jDsj8JcUScGpIDA7CpI+NS7biMFoOavpzxAdTB/o1CURozJ0iQn79g==,iv:koAvbUmMPe9ojnR4FSAvYPlWwUd5EulRkUwiRCzJ6u8=,tag:BWI5g2t3BijKA5pIywLI5g==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb0NvRjRlNWhLMitBUlBJ
        RnpNY1lkNmZDMnVXekdMZEJrd1NnQXA0RHlrCnFsRlFyL1U4T3BmUDZvOVBGeFc0
        U3RSUmNYRjNiN3I4NkNCTG1VWWlkcGsKLS0tIG9rOEN6cmh3UHF6Wjh3RVA3RklX
        NXNISkxsNE5neGd0YkpNd01YWXNISjAKmFBnq6j3woJGQc2tJoqMRQhinQudh0/G
        8nMsFo+d4VSMeg7oaS6Bs20yIazwzVQ5zN52DriWWAMoB0ZzKDTSCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-21T11:48:30Z"
  mac: ENC[AES256_GCM,data:N/ClhFiwfB1Iu294mUgR/3WUg1QUqiHr5qLwLir6K+wOj73UouKQoQbUrPsD+BG1AjiemRpmVYvkzP7JgQ7ReSkADYE0/fN13AH2xBrq3/+4H4mXsxz5kN9kPqMsWEbtlLyan79jH2zhMLzg+bdUvfBDDHTVHyePNqYn3YbT30A=,iv:49AcpnJSt7Ng3/Qci3HP3gnKWp6i+kjz3g7FIMBi49c=,tag:axa8MQQIEA+zPU3SVj/m6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
