{
 "title": "Kubernetes Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "label_values(up, cluster)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum Kubernetes CPU request per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of running pods per node",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Running\"}) by (node,phase)) by (node)",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "CPU Cores by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores) by (node)",
     "legendFormat": "{{node}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top 10 High Cardinality Series",
   "type": "bargauge",
   "description": "The query calculates the number of time series per job and metric name. Only the top 10 are shown.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,(count by (job, __name__) ({__name__!=\"\"})))",
     "legendFormat": "{{__name__}} - {{job}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{app=\"event-exporter\"}"
    }
   ]
  }
 ]
}