apiVersion: v1
kind: Secret
metadata:
  name: copyparty-secret
stringData:
  accounts.conf: ENC[AES256_GCM,data:lEvYC0S9+PKv/mTRtmMQMCShLUyLxJkrKxg8Ssa9vIdHps0fQM571lvfOYWkkeybOqL9HUM=,iv:tN0NxIe/lo7bPnZQZ18fyn/Mw4ogGFuVzB9xvuUJaCA=,tag:v2gUdyT+skswEPhjybAM7A==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZjhNdmNndlc0Rzd6ZEkr
        emlvRkZoTTlNMld4MGluMWhEZXpFWjdXdmlFCmJiU0JaVXlGK082ODRocGhkc3pF
        YmZZRW1pV2xBUlFNenhJYWNWK3lza0UKLS0tIE1iaFVNOVEvL1VSNTArKy8xY1ZW
        TW9HYXVmaUNvY2NwVUpsWjBBU2JDd1kKifytXJdPIRO5PKHNAwMSACzyKQBQGb4s
        0XMOp3Ikx7nt3KS4pDKj10v/KUgPVV70VwGpTXUr/IReguRDtPc6NQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-08T19:59:20Z"
  mac: ENC[AES256_GCM,data:wUMfDNd3IguAiWYUK/kHgARoqqVJ063s9O1CIkJ8ND6zksESilPsnzaIzfRndXDQGtvcuIbyMmF5CF53OkuIjv0ypjyTNVzNH1Kq+kD5HcllwKXID8gaQoIm+mZ7MV3dGcL+uADklafUUFx2rmSC4efWy33cSFoTTnXNrIPFBpA=,iv:aF0VfQZRqP+SsNR5cIGY9U7cL4DMDARkBpDCFDpf1as=,tag:kZWQ0Z8sku6fJc4duB2gBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
