---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: canary-test
spec:
  dependsOn:
    - name: podinfo
  path: ./kubernetes/apps/default/canary/test
  targetNamespace: default
