---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-workspace-config
  namespace: develop
spec:
  dependsOn:
    - name: forgejo-workspace-secrets
  interval: 5m
  path: ./kubernetes/apps/develop/workspace/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: forgejo-workspace-auth
    namespace: develop
  targetNamespace: develop
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-workspace-secrets
  namespace: develop
spec:
  interval: 5m
  path: ./kubernetes/apps/develop/workspace/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: forgejo-workspace-auth
    namespace: develop
  targetNamespace: develop
