---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  chartRef:
    kind: OCIRepository
    name: openbao
  values:
    injector:
      enabled: false
    ui:
      enabled: true
    serverTelemetry:
      serviceMonitor:
        enabled: true
    server:
      updateStrategyType: RollingUpdate
      logFormat: json
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      dataStorage:
        enabled: true
        size: 5Gi
        storageClass: openebs-hostpath
      extraSecretEnvironmentVars:
        - envName: BAO_UNSEAL_KEY
          secretName: openbao-unseal
          secretKey: BAO_UNSEAL_KEY
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            cluster_name = "openbao"

            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = 1
              telemetry {
                unauthenticated_metrics_access = true
              }
            }

            storage "raft" {
              path = "/openbao/data"
              retry_join {
                leader_api_addr = "http://openbao-0.openbao-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://openbao-1.openbao-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://openbao-2.openbao-internal:8200"
              }
            }

            seal "static" {
              current_key_id = "unseal-v1"
              current_key = "env://BAO_UNSEAL_KEY"
            }

            telemetry {
              prometheus_retention_time = "5m"
              disable_hostname = true
            }

            service_registration "kubernetes" {}
