---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./migration.yaml
  - ./ck-push-test.yaml
  - ./snapshot.yaml

configMapGenerator:
  - name: ck-push-test
    files:
      - ck-push-test.js=./ck-push-test.js
  - name: ck-push-test-config
    files:
      - ck-push-test.yaml=./ck-push-test.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
