---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ck-push-test-cron
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: k6-observability
          containers:
            - name: kubectl
              image: bitnami/kubectl@sha256:e2b97dde9666986c61c56d49aae85a714b89b69392baa531438e74ec34096fb4
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: k6-yaml
                  mountPath: /tmp/
              command:
                - /bin/bash
              args:
                - -c
                - 'kubectl delete -f /tmp/ck-push-test.yaml; kubectl apply -f /tmp/ck-push-test.yaml'
          restartPolicy: OnFailure
          volumes:
            - name: k6-yaml
              configMap:
                name: ck-push-test-config
