---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.2.2
    digest: sha256:2b8e2c5c3031810cad7d5bb3984ba5d43627b8ce2ac31d6f8fa6fe830877c2bc
  url: oci://ghcr.io/goauthentik/helm-charts/authentik