---
metrics: true

storage:
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db
  type: sqlite

ui:
  buttons:
    - name: Github
      link: https://github.com/oscaromeu
    - name: Homelab
      link: https://github.com/oscaromeu/home-ops
  default-sort-by: group
  header: Status
  link: https://github.com/oscaromeu
  title: Status | Gatus

web:
  port: ${GATUS_WEB_PORT}
