---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0@sha256:1d56ff606ad14fd1255732019d60540f0982c60cf7afb9f66573e6e513f6bbcc
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
