---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.2@sha256:294a761ca972ea11ae79b9219960ca13a5337a1cbb550604c151586d266159eb
  url: oci://quay.io/jetstack/charts/cert-manager
