---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pushgateway
spec:
  interval: 15m
  url: oci://ghcr.io/prometheus-community/charts/prometheus-pushgateway
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.7.0
