---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-c
spec:
  chartRef:
    kind: OCIRepository
    name: app-c
  values:
    controllers:
      app-c:
        containers:
          app:
            image:
              repository: ghcr.io/oscaromeu/fastapi-observability/app
              tag: latest@sha256:d797e9ef2cca686789c55d3d8f0b84669c589615ed0ff57c4812b7565ef22af0
            env:
              TARGET_ONE_HOST: app-a
              TARGET_TWO_HOST: app-b
              APP_NAME: app-c
              OTLP_GRPC_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4317
              OTEL_RESOURCE_ATTRIBUTES: service.name=app-c
              OTEL_METRICS_EXPORTER: none
    service:
      app:
        ports:
          http:
            port: 8000
    route:
      app:
        hostnames: ["app-c.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
