---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-c-cron
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: k6-observability
          containers:
            - name: kubectl
              image: bitnami/kubectl@sha256:13f055d594719a59102c67d2b0c57c92f74c7fc86a02fb2e18736999082e0848
              volumeMounts:
                - name: k6-yaml
                  mountPath: /tmp/
              command:
                - /bin/bash
              args:
                - -c
                - 'kubectl delete -f /tmp/test.yaml; kubectl apply -f /tmp/test.yaml'
          restartPolicy: OnFailure
          volumes:
            - name: k6-yaml
              configMap:
                name: app-c-config