{
 "title": "Elastic Overview",
 "tags": [
  "elasticsearch",
  "es-cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "In Events/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_events_in_total{component_type=\"kubernetes_logs\", pod_namespace!=\"\"}[$__interval]))",
     "legendFormat": "Events In"
    }
   ]
  },
  {
   "title": "Out Events/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_events_out_total{component_type=\"redis\"}[$__interval]))",
     "legendFormat": "Event out"
    }
   ]
  },
  {
   "title": "App Indices",
   "type": "stat",
   "description": "Number of indices not starting with a dot (.)",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\",index!~\"\\\\..*\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "description": "On all shards",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Primary Segments",
   "type": "stat",
   "description": "On primary shards\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Level Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"yellow\"}==1)+2 or\n(elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"green\"}==1)+4 "
    }
   ]
  },
  {
   "title": "CPU  Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total Indices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "stat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "description": "On all nodes\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_total{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_pool_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "stat",
   "description": "% Memory used by selected nodes, both heap and non-heap",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Shards",
   "type": "stat",
   "description": "All shards, both primary and replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "description": "Number of shards which are relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Shards",
   "type": "stat",
   "description": "Number of shards which are delayed relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "Number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Nodes & Indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Status",
   "type": "table-old",
   "description": "Current status of all nodes in cluster\n\n###### Notes\n\n+ `Blue`: constant value\n+ `Fds`: File Descriptors\n+ `Throttle`: flag `is_throttled`\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (name) (elasticsearch_os_cpu_percent{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (name) (elasticsearch_os_load5{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Load Average"
    },
    {
     "expr": "sum by (name) (elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) / sum by (name) (elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) * 100",
     "legendFormat": "JVM Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Disk Free Space"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "Master Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"data\"})",
     "legendFormat": "Data Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"ingest\"})",
     "legendFormat": "Ingest Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"client\"})",
     "legendFormat": "Client Node"
    },
    {
     "expr": "1 - sum by (name) (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) / sum by (name) (elasticsearch_filesystem_data_size_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "% Disk Used"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_store_size_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Index Store Data"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_memory_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Segment Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_count{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Segment Count"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_open_files_count{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_max_files_descriptors{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_indexing_is_throttled{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Indices Status on Primary Shards",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_docs_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "A"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_deleted_docs_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "B"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "C"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "D"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "E"
    },
    {
     "expr": "count by (index) (elasticsearch_indices_shared_docs{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "F"
    }
   ]
  },
  {
   "title": "Cluster Indexing - $cluster",
   "type": "graph",
   "description": "Indexing rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\nsum (rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval])) / \nsum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Cluster Search - $cluster",
   "type": "graph",
   "description": "Searching rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for those requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(sum(rate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_scroll_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_suggest_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n) /\nsum(rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Indexing ReqRate (req/s)",
   "type": "graph",
   "description": "Indexing rate on data nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search Query ReqRate (req/s)",
   "type": "graph",
   "description": "Search query rate on data nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Times Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Search Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Indexing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merging Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Refresh Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Throttle Time for Index Store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Documents by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merged Documents / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Documents Index Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Merged Bytes / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents Deleted Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "locale", "label": "docs/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Usage - $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "repeat": "name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Max heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Used heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"non-heap\"}",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} / elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} * 100",
     "legendFormat": "% Used Heap"
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-\n(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} /\nelasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})\n)*100",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "Disk Read/Write Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Segments on Nodes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OS Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OS CPU Usage",
   "type": "graph",
   "description": "% CPU used by OS",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "description": "% CPU used by process",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "percent", "label": "% CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}