apiVersion: v1
kind: Secret
metadata:
  name: podinfo-github-auth
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:8+wH3CjkFR5+ZDOBqXKmC248qnHa5wP+N100x+kd2doxMIQ6nyItOPCfgtNLQ+jEOAYB3v6a3xNS932RqP2HCgaMKnCQrI4eI0Noom/0wuH3Wt2aqWGrmGGLyU4jmUv/yJNRc5Yg2Y7CnV01GNuvQQpIhgJus6fKFuBaTpF+qX/EW4bAxpLngf8O35ZRJkSrF45Zn5T3gLUWJngfFGD6MFdK5LxJBlb4kPxN7EAMo7mSxuMX1KT78Rnsq4fbHOcNhMruRAn24XTun0SMeVt3YGjHfNiHmfQB5kF9ngRE7PAq89ncvbRkbN/n7F2+w2syCCeeuL1agxunpfz+6quftOEr7q59Yh/opboAWqinaxjiXzGp7VUEzC20BR637qUdi9TZ0z9XsB7AZnGIRj6fknk0Zk8uOUzqkmV/CGnYfjyg5mqIV1Mhk2yAh4Jo4lu+j3lc/YJ7j0RvM80l9JzdoaA09oK9CNePrGnyzGB3Nz4UZgB70rIhfSN56H3HATabbB6/w13s+J5ljy7N8i5TmXFImctD0JLYQmiq,iv:Fo037pfyFThr8phukRdQj9lXKcJOES71/RDjL18F1Hw=,tag:q1/FrGxOChZDQ+3yGTzZJg==,type:str]
  identity.pub: ENC[AES256_GCM,data:KslWm0qqD6RUySNBEgDVI1CZbtRSWLVL0R7M+SCTTaz/CoOJG3I6aXT76duJu9y1NLHOoaas47Mke8H4OEyASmQN9r9RY7VArACI0qYFKrTV9T4KGuW72hGJZk59A0nlmdPepII=,iv:7AdOhDA+H3DOXt0H9dPskKQv6zAEL7HHKnbrS88kyJ0=,tag:GP/NpzB9dJeuBuTjc50McQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:fELSlBzCh9YgLcssl/GHpouRhplKujTM3DhF/xYMvxQ+r8YTHaKzAxaCJLMkmFjC1IFJ4MIdT0eotiAgCn0t9bjxaR6oilEvnPr0TP2SlVX3B4HIUfQAMexFPpo=,iv:tjWHdtAymqDnT8XshM5BZeOnZ0YulPUdU94Aigs8Lwk=,tag:eu6wvbyugrFjSZKEZgTfCg==,type:str]
sops:
  age:
    - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFckNWdCt1MTZESDl1UlBF
        SG50L0V1V3Nzemk5NXB3Q1l0S1BPUzl0M0hrCkhFZWZCZ1Z0blpKelY2NzZEVVRM
        UWJGZm9Hc3d5SGhZK2xzNnBMYmI2ZTQKLS0tIGRsanY3cUFUamRwbzU0bGlCc3ow
        cnJwWlkvc0NlVUNhS2tkK3hnVU1DZ28KmjVrMkMepQ0CyIP8rch2sI20DiM70Uvf
        ZtU/mqUeHaKSQM4qoILmvfHehxTVNnSoB38eVCmA8ZS0sySCHu/WyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-19T09:50:49Z"
  mac: ENC[AES256_GCM,data:OjOMrNorlZJjUdZYIY/AtFt28opA5C03BzF1xZs2ZBPadA9TxLb/OAGcvH9K+qOW/J2VSL6/IBJYT7Z0VOZkpNuUf8pI+asOkS5Vu++qOq9DuCt/AXCw9SlMlSceWwQahpZDqX6ckdwuhHeJVGgZC0DT5xAq1ZvnaP9D9QfA8F8=,iv:H4zQ5M28KQ0ABva741ZYIQA+eY9f737zeKknhpII/Dg=,tag:+eB0V9FztWAVtN+A6Jkxtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
