---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.7.2@sha256:02cfb2d2e9a31386f850a1ef3ab2a7a18a489eb2140a35c700c73b9b72b231f8
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
