---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: pipelines-forwarder
    files:
      - kubernetes-forwarder.yaml=./kubernetes-forwarder.yaml
generatorOptions:
  disableNameSuffixHash: true
