---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: icecast
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: icecast-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        ICECAST_SOURCE_PASSWORD: "{{ .ICECAST_SOURCE_PASSWORD }}"
        ICECAST_RELAY_PASSWORD: "{{ .ICECAST_RELAY_PASSWORD }}"
        ICECAST_ADMIN_PASSWORD: "{{ .ICECAST_ADMIN_PASSWORD }}"
        ICECAST_ADMIN_EMAIL: admin@oscaromeu.io
        ICECAST_ADMIN_USERNAME: admin
  dataFrom:
    - extract:
        key: icecast
