---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ip-logger.yaml
  - ./snapshot.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: ip-logger
    files:
      - ip-logger.js=./ip-logger.js
  - name: ip-logger-config
    files:
      - ip-logger.yaml=./ip-logger.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
