# snapshotter.yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-logger-cron
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: k6-observability
          containers:
            - name: kubectl
              image: bitnami/kubectl@sha256:323998cf83a2332f6761706df910870a3fa24dd8d4b999db977aa322de553399
              tag: sha256-f79ebae1ff869758d46262ecb417e3526805669a2c61623e74ff6e4cf1d82bca
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: k6-yaml
                  mountPath: /tmp/
              command:
                - /bin/bash
              args:
                - -c
                - 'kubectl delete -f /tmp/ip-logger.yaml --ignore-not-found; kubectl apply -f /tmp/ip-logger.yaml'
          restartPolicy: OnFailure
          volumes:
            - name: k6-yaml
              configMap:
                name: ip-logger-config
