{
 "title": "Vector 1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vector_uptime_seconds{job=~\".*\"}, job)"
    }
   },
   {
    "name": "component_kind",
    "label": "Kind",
    "query": {
     "query": "label_values(vector_component_sent_event_bytes_total{job=~\".*$job.*\"}, component_kind)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(vector_uptime_seconds{job=~\".*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pods CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$job cpu",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod, namespace) (pod:container_cpu_usage:sum{pod=~'.*$job.*',namespace=~'$namespace',container=''}) < 1)",
     "legendFormat": "Low (< 1CPU)"
    },
    {
     "expr": "count((sum by (pod, namespace) (pod:container_cpu_usage:sum{pod=~'.*$job.*',namespace=~'$namespace',container=''}) >= 1) < 4)",
     "legendFormat": "Normal (1-4 CPU)"
    },
    {
     "expr": "count(sum by (pod, namespace) (pod:container_cpu_usage:sum{pod=~'.*$job.*',namespace=~'$namespace',container=''}) >= 4)",
     "legendFormat": "High (> 4 CPU)"
    }
   ]
  },
  { "title": "Pods Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$job mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 7 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod, namespace) (container_memory_working_set_bytes{pod=~'.*$job.*',namespace=~'$namespace',container=''}) < 1073741824)",
     "legendFormat": "Low (< 1GB)"
    },
    {
     "expr": "count((sum by (pod, namespace) (container_memory_working_set_bytes{pod=~'.*$job.*',namespace=~'$namespace',container=''}) >= 1073741824) < 4294967296)",
     "legendFormat": "Normal (1-4GB)"
    },
    {
     "expr": "count(sum by (pod, namespace) (container_memory_working_set_bytes{pod=~'.*$job.*',namespace=~'$namespace',container=''}) >= 4294967296)",
     "legendFormat": "High (> 4GB)"
    }
   ]
  },
  { "title": "Discard rate current / sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 13 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n            sum by(job,component_kind)(rate(vector_component_discarded_events_total{job=~\".*$job.*\",component_kind=\"sink\",namespace=~\"$namespace\"}[1m]))\n          /\n            sum by(job,component_kind)(rate(vector_component_received_events_total{job=~\".*$job.*\",component_kind=\"sink\",namespace=~\"$namespace\"}[1m]))\n          )",
     "legendFormat": "discard %"
    },
    {
     "expr": "sum by(job,component_kind)(rate(vector_component_discarded_events_total{job=~\".*$job.*\",component_kind=\"sink\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "discard count"
    }
   ]
  },
  { "title": "Error rate current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 18 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job)(rate(vector_component_errors_total{job=~\".*$job.*\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "error count"
    }
   ]
  },
  {
   "title": "Events rate current / $component_kind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "component_kind"
  },
  {
   "title": "$job",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 23 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, component_kind,component_type) (rate(vector_component_sent_events_total{job=~\".*$job.*\",component_type!=\"prometheus_exporter\", component_kind=\"$component_kind\", component_type!=\"internal_metrics\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{component_type}}"
    }
   ]
  },
  {
   "title": "Errors type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job errors types",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 23 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (component_name, component_kind,component_type,error_type) (rate(vector_component_errors_total{job=~'.*$job.*',namespace=~'$namespace'}[1m])) > 0",
       "legendFormat": "{{component_kind}}/{{component_name}}/{{component_type}}/{{error_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events sent count / $component_kind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "component_kind",
   "collapsed": true,
   "panels": [
    {
     "title": "$job",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 40 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, component_kind,component_type,component_name) (irate(vector_component_sent_events_total{job=~\".*$job.*\",component_type!=\"prometheus_exporter\", component_kind=\"$component_kind\", component_type!=\"internal_metrics\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{component_type}} / {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events sent bytes / $component_kind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "component_kind",
   "collapsed": true,
   "panels": [
    {
     "title": "$job",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 48 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,component_kind,component_type,component_name)(rate(vector_component_sent_event_bytes_total{job=~\".*$job.*\",component_kind=\"$component_kind\", component_type!=\"internal_metrics\",component_type!=\"prometheus_exporter\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{component_type}} / {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job sink",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 56 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, component_kind,component_type,component_name) (vector_buffer_events{job=~\".*$job.*\",component_type!=\"prometheus_exporter\", component_kind!=\"transform\", component_type!=\"internal_metrics\",namespace=~\"$namespace\"})",
       "legendFormat": "{{component_type}} / {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 64 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by (job,component_kind,component_type,component_name)(vector_buffer_byte_size{job=~\".*$job.*\",component_type!=\"prometheus_exporter\",component_type!=\"internal_metrics\",namespace=~\"$namespace\"})",
       "legendFormat": "{{component_kind}} / {{component_type}} / {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job sink",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 72 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,component_kind,component_type,component_name)(rate(vector_buffer_received_bytes_total{job=~\".*$job.*\",component_type!=\"prometheus_exporter\",component_type!=\"internal_metrics\",namespace=~\"$namespace\"}[1m])) - sum by (job,component_kind,component_type,component_name)(rate(vector_buffer_sent_bytes_total{job=~\".*$job.*\",component_type!=\"prometheus_exporter\",component_type!=\"internal_metrics\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{component_type}} / {{component_name}}"
      }
     ]
    }
   ]
  }
 ]
}