---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zot-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        # Full htpasswd line(s), bcrypt: htpasswd -nbB oscar <password>
        htpasswd: "{{ .htpasswd }}"
  dataFrom:
    - extract:
        key: zot
