---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  values:
    serviceType: LoadBalancer
    service:
      annotations:
        lbipam.cilium.io/ips: "${K8S_GATEWAY_LB}"
      externalTrafficPolicy: Cluster
    servers:
      - zones:
          - zone: .
        port: 1053
        servicePort: 53
        plugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: k8s_gateway
            parameters: "${SECRET_DOMAIN}"
            configBlock: |-
              apex k8s-gateway.network
              ttl 1
              resources HTTPRoute Service
              fallthrough
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . 1.1.1.1 1.0.0.1
          - name: loop
          - name: reload
          - name: loadbalance
