---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  values:
    controllers:
      recyclarr:
        type: cronjob
        cronjob:
          schedule: 0 5 * * *
          successfulJobsHistory: 1
          failedJobsHistory: 1
          concurrencyPolicy: Forbid
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.1@sha256:73303ba5ee647b6492fee917d3a781c6e59b6cab08f9dfce9482a950846f564f
            args:
              - sync
            env:
              TZ: ${TZ}
            envFrom:
              - secretRef:
                  name: recyclarr
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    configMaps:
      config:
        data:
          recyclarr.yml: |
            sonarr:
              series:
                base_url: http://sonarr.default.svc.cluster.local:8989
                api_key: !env_var SONARR_API_KEY
                quality_profiles:
                  - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
                    reset_unmatched_scores:
                      enabled: true
                custom_format_groups:
                  add:
                    - trash_id: 158188097a58d7687dee647e04af0da3 # Golden Rule HD
                      exclude:
                        - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
                    - trash_id: 74aff4168620ed49dcc67e92b2c2a5b4 # Language Profiles
                    - trash_id: 85fae4a2294965b75710ef2989c850eb # Streaming Services HD/UHD boost
                    - trash_id: 59c3af66780d08332fdc64e68297098f # Unwanted Formats
                      exclude:
                        - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
                        - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
            radarr:
              movies:
                base_url: http://radarr.default.svc.cluster.local:7878
                api_key: !env_var RADARR_API_KEY
                quality_profiles:
                  - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
                    reset_unmatched_scores:
                      enabled: true
                custom_format_groups:
                  add:
                    - trash_id: f8bf8eab4617f12dfdbd16303d8da245 # Golden Rule HD
                      exclude:
                        - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
                    - trash_id: a3ac6af01d78e4f21fcb75f601ac96df # Unwanted Formats
                      exclude:
                        - 90a6f9a284dff5103f6346090e6280c8 # LQ
                        - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: recyclarr
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
