---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          create: false
          name: homepage
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
            env:
              TZ: Europe/Madrid
              HOMEPAGE_ALLOWED_HOSTS: "home.${SECRET_DOMAIN}"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs

    route:
      app:
        hostnames:
          - "home.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
