---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peertube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: peertube-secret
    template:
      engineVersion: v2
      data:
        # PostgreSQL configuration
        PEERTUBE_DB_HOST: "{{ .host }}"
        PEERTUBE_DB_PORT: "5432"
        PEERTUBE_DB_USERNAME: "{{ .user }}"
        PEERTUBE_DB_PASSWORD: "{{ .password }}"
        PEERTUBE_DB_SSL: "false"
        # Web configuration
        PT_INITIAL_ROOT_PASSWORD: "{{ .PEERTUBE_ADMIN_PASSWORD }}"
        PEERTUBE_ADMIN_EMAIL: "{{ .PEERTUBE_ADMIN_EMAIL }}"
  dataFrom:
    - extract:
        key: peertube