---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app peertube
spec:
  chartRef:
    kind: OCIRepository
    name: outline
  values:
    controllers:
      peertube:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &envFrom
              - secretRef:
                  name: postgres-${postgres_cluster_version}-pguser-peertube
        containers:
          app:
            image:
              repository: chocobozzz/peertube
              tag: production-bookworm
            env:
              NODE_ENV: production
              PEERTUBE_WEBSERVER_HOSTNAME: "{{ .Release.Name }}.${SECRET_DOMAIN}"
              PEERTUBE_WEBSERVER_PORT: "443"
              PEERTUBE_WEBSERVER_HTTPS: "true"
              PEERTUBE_TRUST_PROXY: '["loopback", "uniquelocal"]'
              PEERTUBE_SMTP_ACTIVE: "false"
              PEERTUBE_SIGNUP_ENABLED: "false"
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/config
                    port: &port 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: peertube
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: peertube
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      videos:
        type: nfs
        server: ${NAS_SERVER_IP}
        path: ${NAS_SERVER_MEDIA_PATH}
        advancedMounts:
          peertube:
            app:
              - path: /downloads
                subPath: Library/Peertube
              - path: /data
                subPath: Library/Peertube/data