---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: clickhouse
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  replicas: 1
  containerTemplate:
    image:
      repository: docker.io/clickhouse/clickhouse-server
      tag: 26.3
      hash: sha256:1f7cd090d5c4e2b8bfe0ea5d8ae6125937e1d932c6371b4d25fbd6088829dc9c
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi
  dataVolumeClaimSpec:
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  keeperClusterRef:
    name: clickhouse
