{
 "title": "Kafka Topic Metrics",
 "description": "Kafka Topic Metrics for Redpanda",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "data_cluster",
    "label": "Data cluster",
    "query": {
     "query": "label_values(vectorized_cloud_data_cluster_name)"
    }
   },
   {
    "name": "redpanda_topic",
    "label": "Topic",
    "query": {
     "query": "label_values(redpanda_kafka_request_bytes_total{redpanda_namespace='kafka', redpanda_topic !~ 'controller|group'}, redpanda_topic)"
    }
   },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Topic : redpanda_topic,Topic\\,Partition : redpanda_topic\\,redpanda_partition"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Topic Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(redpanda_kafka_max_offset{topic!=\"__consumer_offsets\", redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\", redpanda_topic=~\"[[redpanda_topic]]\"}) by ([[aggr_criteria]]))   "
    },
    {
     "expr": "100 * abs((stddev by (redpanda_topic) (sum(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\", redpanda_topic=~\"[[redpanda_topic]]\"}) by (redpanda_topic,redpanda_partition))) /  (avg by (redpanda_topic) ((sum(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\", redpanda_topic=~\"[[redpanda_topic]]\"}) by (redpanda_topic,redpanda_partition)))))"
    },
    {
     "expr": "max by(redpanda_topic)(redpanda_kafka_partitions{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\", redpanda_topic=~\"[[redpanda_topic]]\"})"
    },
    {
     "expr": "max by(redpanda_topic)(redpanda_kafka_replicas{redpanda_namespace=\"kafka\",redpanda_cloud_data_cluster_name=~\"\", redpanda_topic=~\"[[redpanda_topic]]\"})"
    },
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\",redpanda_request=\"produce\"}[1m])) by (redpanda_topic)"
    },
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\",redpanda_request=\"consume\"}[1m])) by (redpanda_topic)"
    }
   ]
  },
  {
   "title": "Records Received per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]]) (rate(redpanda_kafka_max_offset{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[1m]))",
     "legendFormat": "{{redpanda_topic}}:{{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Write Throughput per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redpanda_kafka_request_bytes_total{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_request=\"produce\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{redpanda_topic}}:{{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Read Throughput per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redpanda_kafka_request_bytes_total{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_request=\"consume\",vectorized_cloud_data_cluster_name=~\"[[data_cluster]]\"}[1m])) by ([[aggr_criteria]])",
     "legendFormat": "{{redpanda_topic}}:{{redpanda_partition}}"
    }
   ]
  }
 ]
}