---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-gitlab
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: podinfo-gitlab-auth
  url: ssh://git@gitlab.com/oscaromeu/podinfo-gitlab.git
