{
 "title": "Cluster / Namespace Available Resources",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "\n### Requests per node" } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "options": { "content": "\n### Limits per node" } },
  {
   "title": "CPU Requesteable Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(20,sum by(kube_cluster_name,node)(kube_node_status_allocatable{resource=\"cpu\",kube_cluster_name=~\".*\"}) -\nsum by (kube_cluster_name,node)(kube_pod_container_resource_requests{resource=\"cpu\",kube_cluster_name=~\".*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free CPU Cores per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(20,sum by (kube_cluster_name,node) (kube_node_status_capacity{resource=\"cpu\",kube_cluster_name=~\".*\"})  -(sum(rate(container_cpu_usage_seconds_total[5m])) by (node)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requesteable Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,sum by (kube_cluster_name,node)(kube_node_status_allocatable{resource=\"memory\",kube_cluster_name=~\".*\"})-\nsum by (kube_cluster_name,node)(kube_pod_container_resource_requests{resource=\"memory\",kube_cluster_name=~\".*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,sum by (kube_cluster_name, node) (kube_node_status_capacity{resource=\"memory\"}) - sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (node))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}