{
 "title": "Canary Checker Details",
 "description": "Detailed information regarding specific canary checks",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(canary_check_info, namespace)"
    }
   },
   {
    "name": "Canary",
    "query": {
     "query": "label_values(canary_check_info{namespace=\"$Namespace\"}, canary_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "marcusolsson-hexmap-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min(canary_check{canary_name=\"$Canary\", namespace=\"$Namespace\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "max by(name, type, exported_endpoint) (canary_check_info{canary_name=\"$Canary\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(canary_check{canary_name=\"$Canary\", namespace=\"$Namespace\"})by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "90% Duration Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, canary_check_duration_bucket{canary_name=\"$Canary\", namespace=\"$Namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "90% Response Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, canary_check_histogram_bucket{canary_name=\"$Canary\", namespace=\"$Namespace\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}