---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chartRef:
    kind: OCIRepository
    name: podinfo
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    httpRoute:
      enabled: true
      hostnames:
        - podinfo.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
