---
- name: Get absolute path to this Git repository # noqa: command-instead-of-module
  ansible.builtin.command: git rev-parse --show-toplevel
  delegate_to: localhost
  become: false
  register: repository_path
  changed_when: false
  check_mode: false

- name: Copy kubeconfig to the project directory
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ repository_path.stdout }}/kubeconfig-{{ cluster_name }}"
    flat: true

- name: Update kubeconfig with the node address
  delegate_to: localhost
  become: false
  ansible.builtin.replace:
    path: "{{ repository_path.stdout }}/kubeconfig-{{ cluster_name }}"
    regexp: https://127.0.0.1:6443
    replace: "https://{{ ansible_host }}:6443"
