{
 "title": "Kubernetes Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Number of running pods per node",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Running\"}) by (node,phase)) by (node)",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "CPU Cores by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores) by (node)",
     "legendFormat": "{{node}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum Kubernetes CPU request per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"vector\"}"
    }
   ]
  }
 ]
}