---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.1
    digest: sha256:dc8d9f0139d8d606e198e947a8d9db089f820065f7f56cd4064d327ddf080d7c
  url: oci://ghcr.io/external-secrets/charts/external-secrets