---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.0
    digest: sha256:cd69455c31b4ee6a185afa2b8d321aa6b7d6f4f50e9c997c9dbd4a7dce3dc4f4
  url: oci://ghcr.io/home-operations/charts-mirror/openebs