---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: peertube-admin-password
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: peertube-secret
  namespace: databases
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peertube-extra-secrets
  namespace: databases
spec:
  refreshInterval: "24h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: peertube-extra-secrets
    creationPolicy: Owner
    template:
      data:
        PT_INITIAL_ROOT_PASSWORD: "{{ .admin_password }}"
        PEERTUBE_SECRET: "{{ .peertube_secret }}"
        PEERTUBE_ADMIN_EMAIL: "{{ .admin_email }}"
        PEERTUBE_DB_SSL: "false"
        PEERTUBE_REDIS_HOSTNAME: "valkey.databases.svc.cluster.local"
        PEERTUBE_REDIS_PORT: "6379"
  data:
    - secretKey: admin_email
      remoteRef:
        key: admin-email
        property: username
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: peertube-admin-password
      rewrite:
        - regexp:
            source: "password"
            target: "admin_password"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: peertube-secret
      rewrite:
        - regexp:
            source: "password"
            target: "peertube_secret"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: peertube-extra-secrets
  namespace: databases
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          property: PT_INITIAL_ROOT_PASSWORD
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PT_INITIAL_ROOT_PASSWORD
    - conversionStrategy: None
      match:
        remoteRef:
          property: PEERTUBE_SECRET
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PEERTUBE_SECRET
    - conversionStrategy: None
      match:
        remoteRef:
          property: PEERTUBE_ADMIN_EMAIL
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PEERTUBE_ADMIN_EMAIL
    - conversionStrategy: None
      match:
        remoteRef:
          property: PEERTUBE_DB_SSL
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PEERTUBE_DB_SSL
    - conversionStrategy: None
      match:
        remoteRef:
          property: PEERTUBE_REDIS_HOSTNAME
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PEERTUBE_REDIS_HOSTNAME
    - conversionStrategy: None
      match:
        remoteRef:
          property: PEERTUBE_REDIS_PORT
          remoteKey: postgres-${postgres_cluster_version}-pguser-peertube
        secretKey: PEERTUBE_REDIS_PORT
  deletionPolicy: Delete
  refreshInterval: 5m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: peertube-extra-secrets
  template:
    data:
      PT_INITIAL_ROOT_PASSWORD: '{{ index . "PT_INITIAL_ROOT_PASSWORD" | toString }}'
      PEERTUBE_SECRET: '{{ index . "PEERTUBE_SECRET" | toString }}'
      PEERTUBE_ADMIN_EMAIL: '{{ index . "PEERTUBE_ADMIN_EMAIL" | toString }}'
      PEERTUBE_DB_SSL: '{{ index . "PEERTUBE_DB_SSL" | toString }}'
      PEERTUBE_REDIS_HOSTNAME: '{{ index . "PEERTUBE_REDIS_HOSTNAME" | toString }}'
      PEERTUBE_REDIS_PORT: '{{ index . "PEERTUBE_REDIS_PORT" | toString }}'
    engineVersion: v2
    mergePolicy: Merge
  updatePolicy: Replace
