---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  chartRef:
    kind: OCIRepository
    name: fluent-bit
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    existingConfigMap: fluentbit
    image:
      repository: cr.fluentbit.io/fluent/fluent-bit
      tag: 5.0.7-debug@sha256:f64130680355a6e6394b96bfa69dc96632396047209a631ea348d46ce2c5a953
    args:
      - --workdir=/fluent-bit/etc
      - --config=/fluent-bit/etc/conf/fluentbit.yaml
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true
    logLevel: warn
    extraVolumes:
      - name: parsers
        configMap:
          defaultMode: 420
          name: parsers
      - name: pipelines
        configMap:
          defaultMode: 420
          name: pipelines
      - name: topic-cluster-apps-logs-certs
        secret:
          secretName: topic-cluster-apps-logs-certs
          defaultMode: 420   # optional, controls permissions
    extraVolumeMounts: 
      - name: parsers
        mountPath: /fluent-bit/etc/conf/parsers.d/
      - name: pipelines
        mountPath: /fluent-bit/etc/conf/pipelines.d/
      - name: topic-cluster-apps-logs-certs
        mountPath: /fluent-bit/etc/secrets/
        readOnly: true
